---

- name: "get home directory {{item.owner}}"
  getent:
    database: passwd
    key: "{{item.owner}}"
    split: ":"

- set_fact:
    _home_directory: "{{getent_passwd[item.owner][4]}}"

- name: "get home directory {{ item }}."
  shell: >
    getent passwd {{ item }} | cut -d: -f6
  changed_when: false
  register: _home_directory

- name: insert alias ll into .bashrc
  lineinfile:
    dest: "{{_home_directory}}/.bashrc"
    regexp: '^\s*alias ll='
    state: present
    line: 'alias ll="ls -ls --color"'
  become: true

- name: insert alias grep into .bashrc
  lineinfile:
    dest: "{{_home_directory}}/.bashrc"
    regexp: '^\s*alias grep='
    state: present
    line: 'alias grep="grep --color=auto"'
  become: true
    
- name: change file ownership, group and permissions .bashrc
  file:
    path: "{{_home_directory}}/.bashrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0664'
  become: true
