---

- name: "Get home directory {{ item }}."
  shell: >
    getent passwd {{ item }} | cut -d: -f6
  changed_when: false
  register: user_home

# https://github.com/dysosmus/ansible-completion
- name: "Clone git@github.com:dysosmus/ansible-completion.git to /tmp/ansible-completion/"
  git:
    repo:  git@github.com:dysosmus/ansible-completion.git 
    dest: "/tmp/ansible-completion"
    depth: 1
    accept_hostkey: yes
    key_file: "{{ user_home.stdout }}/.ssh/id_rsa"
  become: true

- name: copy /tmp/ansible-completion/*.bash to /etc/bash_completion.d/
  copy: 
    src: "{{ item.[1] }}"
    dest: /etc/bash_completion.d/
    owner: root
    group: root
    mode: 0744
  with_fileglob: "/tmp/ansible-completion/*.bash"
  become: true

- name: remove /tmp/ansible-completion
  file:
    path: /tmp/completion
    state: absent
  become: true
  
# https://github.com/junegunn/vim-plug
- name: create directory vim autoload
  file:
    path:  "{{ user_home.stdout }}/.vim/autoload"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0664
  become: true

- name: install plug.vim
  shell: |
    curl -fLo {{ user_home.stdout }}/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  become: true
  
# https://github.com/pearofducks/ansible-vim
- name: install VIM syntax highlighting plugin for Ansible
  blockinfile:
    dest: "{{ user_home.stdout }}/.vimrc"
    block: |
      " Plugins will be downloaded under the specified directory.
      call plug#begin('~/.vim/plugged')

      " Declare the list of plugins.
      Plug 'pearofducks/ansible-vim'
  
      " List ends here. Plugins become visible to Vim after this call.
      call plug#end()
  become: true
