---

- name: "get home directory {{item}}"
  getent:
    database: passwd
    key: "{{item}}"
    split: ":"

- set_fact:
    _home_directory: "{{getent_passwd[item][4]}}"

- name: "clone https://github.com/dysosmus/ansible-completion.git to /tmp/ansible-completion/"
  git:
    repo:  https://github.com/dysosmus/ansible-completion.git
    dest: "/tmp/ansible-completion"
    depth: 1
  become: true

- name: copy /tmp/ansible-completion/*.bash to /etc/bash_completion.d/
  copy: 
    src: "{{ file_item }}"
    dest: /etc/bash_completion.d/
    owner: root
    group: root
    mode: 0744
  with_fileglob: "/tmp/ansible-completion/*.bash"
  loop_control:
    loop_var: file_item
  when: '"root" not in _home_directory'
  become: true

- name: remove /tmp/ansible-completion
  file:
    path: /tmp/completion
    state: absent
  become: true
  
- name: create directory vim autoload
  file:
    path:  "{{ _home_directory }}/{{ directory_item }}"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0774
  loop:
    - ".vim/autoload"
  loop_control:
    loop_var: directory_item
  become: true

- name: download plug.vim
  shell: |
    curl -fLo {{ _home_directory }}/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  become: true

- name: set permissions plug.vim
  file:
    path: "{{ _home_directory }}/.vim/autoload/plug.vim"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0774
  become: true
  
- name: install vim syntax highlighting plugin for Ansible
  become: true
  blockinfile:
    create: true
    dest: "{{ _home_directory }}/.vimrc"
    marker: '" {mark} -- ansible managed block ansible-vim plugin --' 
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0774
    block: |
      " Plugins will be downloaded under the specified directory.
      call plug#begin('~/.vim/plugged')

      " Declare the list of plugins.
      Plug 'pearofducks/ansible-vim'
  
      " List ends here. Plugins become visible to Vim after this call.
      call plug#end()

- name: update vim.plug
  shell: |
    vim +PlugUpdate +qall > /dev/null
  become: true
  become_user: "{{ item }}"

- name: insert ANSIBLE_VAULT_PASSWORD_FILE=~/.vault_pass.txt into .bashrc
  lineinfile:
    dest: "{{ _home_directory }}/.bashrc"
    regexp: '^export\sANSIBLE_VAULT_PASSWORD_FILE'
    state: present
    line: 'export ANSIBLE_VAULT_PASSWORD_FILE=~/.vault_pass.txt'
  become: true

