---

- name: schedule apt-get update & upgrade every monday 10pm on raspbian.
  cron: 
    name: "schedule apt-get update & upgrade every cronjob monday 10pm."
    minute: "0"
    hour: "22"
    weekday: "1"
    job: "sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && echo \"finished.\""
  become: true
  when: inventory_hostname in groups['raspbian']

- name: schedule dnf update every monday 10pm on fedora
  cron: 
    name: "schedule dnf update every cronjob monday 10pm."
    minute: "0"
    hour: "22"
    weekday: "1"
    job: "sudo dnf update -y && echo \"finished.\""
  become: true
  when: inventory_hostname in groups['fedora']

- name: schedule reboot cronjob every monday 11:30pm.
  cron:
    name: "schedule reboot every monay 11:30pm."
    minute: "30"
    hour: "23"
    weekday: "1"
    job: "sudo /sbin/reboot"
  become: true
