---

- name: copy jobs
  copy:
    src: "{{item}}"
    dest: "/etc/systemd/system/{{item}}"
    owner: root
    group: root
    mode: 0664
  become: true
  with_items:
    - dnf-update.service
    - dnf-update.timer

- name: start dnf-update.service
  systemd:
    name: dnf-update
    state: started
  become: true

