---

- name: schedule dnf update every monday 10pm on fedora
  cron: 
    name: "schedule dnf update every cronjob monday 10pm."
    minute: "0"
    hour: "22"
    weekday: "1"
    job: "sudo dnf update -y && echo \"finished.\""
  become: true
  when: false

