---

- name: "get home directory {{item}}"
  getent:
    database: passwd
    key: "{{item}}"
    split: ":"

- set_fact:
    _home_directory: "{{getent_passwd[item][4]}}"

- name: "creates {{ _home_directory }}/git directory."
  file: 
    path: "{{ _home_directory }}/git" 
    state: directory 
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0774
  become: true

- name: "check if {{ _home_directory }}/.gitconfig exists."
  stat: 
    path: "{{ _home_directory }}/.gitconfig"
  register: stategitconfig
  become: true

- name: "Touch {{ _home_directory }}/.gitconfig if not exists."
  file: 
    path: "{{ _home_directory }}/.gitconfig"
    state: touch
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0774
  when: stategitconfig.stat.exists is undefined or stategitconfig.stat.exists == False 
  become: true

- name: "Add [user] section to {{ _home_directory }}/.gitconfig"
  lineinfile:
    dest: "{{ _home_directory }}/.gitconfig"
    regexp: '^\[user\]'
    state: present
    insertbefore: 'name'
    line: '[user]'
  become: true

- name: "add 'name = {{ _git_username }}' {{ _home_directory }}/.gitconfig"
  lineinfile:
    dest: "{{ _home_directory }}/.gitconfig"
    regexp: 'name'
    state: present
    insertafter: '\[user\]'
    line: "name = {{ _git_username }}"
  become: true

- name: "add 'email = {{ _git_mailaddress }}' to {{ _home_directory }}/.gitconfig"
  lineinfile:
    dest: "{{ _home_directory }}/.gitconfig"
    regexp: 'email'
    state: present
    insertafter: 'name'
    line: "email = {{ _git_emailaddress }}"
  become: true

- name: "add section [push] to {{ _home_directory }}/.gitconfig"
  lineinfile:
    dest: "{{ _home_directory }}/.gitconfig"
    regexp: '\[push\]'
    state: present
    insertafter: 'email'
    line: '[push]'
  become: true

- name: "add 'default = matching' to {{ _home_directory }}/.gitconfig"
  lineinfile:
    dest: "{{ _home_directory }}/.gitconfig"
    regexp: 'default'
    state: present
    insertafter: '\[push\]'
    line: 'default = matching'
  become: true
