---

- name: "get home directory {{ item }}."
  shell: >
    getent passwd {{ item }} | cut -d: -f6
  changed_when: false
  register: user_home

- name: "creates {{ user_home.stdout }}/git directory."
  file: 
    path: "{{ user_home.stdout }}/git" 
    state: directory 
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0774
  become: true

- name: "check if {{ user_home.stdout }}/.gitconfig exists."
  stat: 
    path: "{{ user_home.stdout }}/.gitconfig"
  register: stategitconfig
  become: true

- name: "Touch {{ user_home.stdout }}/.gitconfig if not exists."
  file: 
    path: "{{ user_home.stdout }}/.gitconfig"
    state: touch
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0774
  when: stategitconfig.stat.exists is undefined or stategitconfig.stat.exists == False 
  become: true

- name: "Add [user] section to {{ user_home.stdout }}/.gitconfig"
  lineinfile:
    dest: "{{ user_home.stdout }}/.gitconfig"
    regexp: '^\[user\]'
    state: present
    insertbefore: 'name'
    line: '[user]'
  become: true

- name: "add 'name = {{ gitusername }}' {{ user_home.stdout }}/.gitconfig"
  lineinfile:
    dest: "{{ user_home.stdout }}/.gitconfig"
    regexp: 'name'
    state: present
    insertafter: '\[user\]'
    line: "name = {{ gitusername }}"
  become: true

- name: "add 'email = {{ gitemailaddress }}' to {{ user_home.stdout }}/.gitconfig"
  lineinfile:
    dest: "{{ user_home.stdout }}/.gitconfig"
    regexp: 'email'
    state: present
    insertafter: 'name'
    line: "email = {{ gitemailaddress }}"
  become: true

- name: "add section [push] to {{ user_home.stdout }}/.gitconfig"
  lineinfile:
    dest: "{{ user_home.stdout }}/.gitconfig"
    regexp: '\[push\]'
    state: present
    insertafter: 'email'
    line: '[push]'
  become: true

- name: "add 'default = matching' to {{ user_home.stdout }}/.gitconfig"
  lineinfile:
    dest: "{{ user_home.stdout }}/.gitconfig"
    regexp: 'default'
    state: present
    insertafter: '\[push\]'
    line: 'default = matching'
  become: true
