# Add entries to /etc/hosts

- name: "Insert hostnames in /etc/hosts"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^{{ item.ipaddress }}[^\d]'
    state: present
    line: '{{ item.ipaddress }}      {{ item.hostname }}               {{ item.fqdn }}'
  loop:
    - { ipaddress: '192.168.11.149', hostname: '4inch',      fqdn: '4inch' }
    - { ipaddress: '192.168.11.',    hostname: '7inch',      fqdn: '7inch' }
    - { ipaddress: '192.168.1.17',   hostname: 'pihole',     fqdn: 'pihole' }
  become: true
    


