---

- name: set correct hostname
  hostname:
    name: "{{inventory_hostname_short}}"
  become: true

- name: create empty ip list
  set_fact: 
    _ip_list: []
    _host_list: []

- name: add ip address with hostnames 
  set_fact:
    _ip_list: "{{(_ip_list + [hostvars[item]._ip_address])|unique}}"
    _host_list: "{{(_host_list + [ { 'ip': hostvars[item]._ip_address, 'fqdn': item } ]) }}"
  with_items: "{{ groups['all'] }}"

- name: add ip address with hostnames + domain
  set_fact:
    _host_list: "{{(_host_list + [ { 'ip': hostvars[item]._ip_address, 'fqdn': item + '.' +_domain } ]) }}"
  with_items: "{{ groups['all'] }}"

- debug:
    msg: "_fqdn: ip:{{item.ip}} <-> fqdn:{{item.fqdn}}" 
  with_items: "{{_fqdns}}"

- name: add ip address with fqdns
  set_fact:
    _ip_list: "{{(_ip_list + [item.ip])|unique}}"
    _host_list: "{{(_host_list + [ { 'ip': item.ip, 'fqdn': item.fqdn } ]) }}"
  with_items: "{{ _fqdns }}"
  
- debug:
    msg: "_host_list: ip:{{item.ip}} -->> fqdn:{{item.fqdn}}" 
  with_items: "{{_host_list}}"
  when: 
    - 'item.ip is defined'
    - 'item.fqdn is defined'

- debug:
    msg: "_ip_list:{{item}}" 
  with_items: "{{_ip_list}}"
  when: 
   - 'item is defined'

- debug:
    msg: "_host_list:{{item.ip}} , {{item.fqdn}}" 
  with_items: "{{_host_list}}"
  when:
    - 'item.ip is defined'
    - 'item.fqdn is defined'

- name: "insert hostnames in /etc/hosts"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^{{item.ip}}[^\d]'
    state: present
    line: '{{item.ip}} {{item.hostname}} {{item.hostname}}.{{_domain}}'
  with_items: "{{_hostnames}}"
  become: true

- name: "insert ip in /etc/hosts"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^{{hostvars[item]._ip_address}}[^\d]'
    state: present
    line: '{{hostvars[item]._ip_address}} {{item}}'
  with_items: "{{groups['all']}}"
  become: true

- name: insert ip + fqdn in /etc/hosts
  replace: 
    dest: '/etc/hosts'
    regexp: '^({{item[1].ip}}\s+(?!.*\b{{item[1].fqdn}}\b).*)$'
    replace: '\1 {{item[1].fqdn}}'
  become: true
  with_nested:
     - "{{_ip_list}}"
     - "{{_host_list}}"
  when: 
    - 'item[0] is defined'
    - 'item[1].ip is defined'
    - 'item[1].fqdn is defined'
    - 'item[0] == item[1].ip'

- name: insert hostnames + ip in /var/lib/pihole/etc-pihole/custom.list
  lineinfile:
    dest: '/var/lib/pihole/etc-pihole/custom.list'
    regexp: '^{{item.ip}}\s+{{item.hostname}}\s*$'
    state: present
    line: '{{item.ip}} {{item.hostname}}'
    owner: root
    group: root
    mode: 0644
  become: true
  with_items: "{{_hostnames}}"
  when: '"pihole" in inventory_hostname'

- name: insert ip + fqdn in /var/lib/pihole/etc-pihole/custom.list
  lineinfile:
    dest: '/var/lib/pihole/etc-pihole/custom.list'
    regexp: '^{{item.ip}}\s+{{item.fqdn}}\s*$'
    state: present
    line: '{{item.ip}} {{item.fqdn}}'
    owner: root
    group: root
    mode: 0644
  become: true
  with_items: "{{_host_list}}"
  when: '"pihole" in inventory_hostname'
