# Add entries to /etc/hosts

- name: "Insert hostnames in /etc/hosts"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^{{ item.ipaddress }}[^\d]'
    state: present
    line: '{{ item.ipaddress }}      {{ item.hostname }}               {{ item.fqdn }}'
  loop:
    - { ipaddress: '192.168.11.149', hostname: 'fed149',     fqdn: 'fed149' }
    - { ipaddress: '192.168.11.143', hostname: 'fed143',     fqdn: 'fed143' }
    - { ipaddress: '192.168.11.157', hostname: 'fed157',     fqdn: 'fed157' }
    - { ipaddress: '192.168.1.17',   hostname: 'pihole',     fqdn: 'pihole' }
  become: true
    


