# Add entries to /etc/hosts

- name: "Insert 192.168.1.17 'pihole' in /etc/hosts"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^192\.168\.1\.17[^\d]'
    state: present
    line: '192.168.1.17      pihole              pihole.bachstraat20'
  become: true
    
- name: "Insert 192.168.1.254 'ziggo' in /etc/hosts"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^192\.168\.1\.254'
    state: present
    line: '192.168.1.254     ziggo               ziggo.bachstraat20'
  become: true
    
- name: "Insert 192.168.11.1 'router' in /etc/hosts"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^192\.168\.11\.1[^\d]'
    state: present
    line: '192.168.11.1      router              router.bachstraat20'
  become: true

- name: "Insert 192.168.11.80 'msi' in /etc/hosts"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^192\.168\.11\.80'
    state: present
    line: '192.168.11.80     msi                 msi.bachstraat20'
  become: true

- name: "Insert 192.168.11.100 'nuc' in /etc/hosts"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^192\.168\.11\.100'
    state: present
    line: '192.168.11.100    nuc                 nuc.bachstraat20'
  become: true

- name: "Insert 192.168.11.114 'lenovo' in /etc/hosts"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^192\.168\.11\.114'
    state: present
    line: '192.168.11.114    lenovo              lenovo.bachstraat20'
  become: true

- name: "Insert 192.168.11.171 'ted1090-3' in /etc/hosts"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^192\.168\.11\.171'
    state: present
    line: '192.168.11.171    ted1090-3           ted1090-3.bachstraat20'
  become: true

- name: "Insert 192.168.11.178 'ted1090-4' in /etc/hosts"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^192\.168\.11\.178'
    state: present
    line: '192.168.11.178    ted1090-4           ted1090-4.bachstraat20'
  become: true


