# Add entries to /etc/hosts

- name: "Insert hostnames in /etc/hosts"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^{{ hostvars[item]._ip_address }}[^\d]'
    state: present
    line: "{{ hostvars[item]._ip_address }}            {{ item }}             {{ item }}.{{ hostvars[item]._domain }}"
  with_items: "{{ groups['all'] }}"
  become: true

