# Add entries to /etc/hosts

- name: "Insert hostnames in /etc/hosts"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^{{ item.ipaddress }}[^\d]'
    state: present
    line: '{{ item.ipaddress }}      {{ item.hostname }}               {{ item.fqdn }}'
  loop:
    - { ipadrress: '192.168.2.13', hostname: '7inch', fqdn: '7inch' }
  become: true
    


