---

- name: "Include Ansible secrets to get emailpassword."
  include_vars: group_vars/vault.yaml

- name: "Configure /etc/ssmtp/ssmtp.conf."
  lineinfile:
    dest: '/etc/ssmtp/ssmtp.conf'
    regexp: "^{{ item.regexp }}"
    state: present
    insertafter: '^#\s*{{ item.insertafter }}'
    line: "{{ item.line }}"
  with_items:
    - { regexp: 'mailhub=',          insertafter: 'mailhub=',           line: 'mailhub={{ _mail_hubhost }}:{{ mail_hubport }}'  }
    - { regexp: 'AuthUser=',         insertafter: 'AuthUser=',          line: "AuthUser={{ _email_address }}"                  }
    - { regexp: 'AuthPass=',         insertafter: 'AuthPass=',          line: "AuthPass={{ _email_password }}"                 }
    - { regexp: 'FromLineOverride=', insertafter: 'FromLineOverride=',  line: 'FromLineOverride=YES'                         }
    - { regexp: 'UseSTARTTLS=',      insertafter: 'UseSTARTTLS=',       line: 'UseSTARTTLS=YES'                              }
    - { regexp: 'UseTLS=',           insertafter: 'UseTLS=',            line: 'UseTLS=YES'                                   }
    - { regexp: 'RewriteDomain=',    insertafter: 'RewriteDomain=',     line: 'RewriteDomain=gmail.com'                      }
    - { regexp: 'Hostname=',         insertafter: 'Hostname=',          line: 'Hostname=localhost'                           }
    - { regexp: 'TLS_CA_File=',      insertafter: 'TLS_CA_File=',       line: "TLS_CA_File={{ TLS_CA_File }}"                }
  become: true

- name: "Write Ansible facts to /tmp/ansible_facts.txt"
  copy: 
    content: "{{ ansible_facts }}" 
    dest: "/tmp/ansible_facts.txt"
  become: true

- name: "Send test e-mail from {{ ansible_hostname }} to {{ _email_address }}, attaching ansible facts."
  mail:
    host: "{{ _mail_hubhost }}"
    port: "{{ _mail_hubport }}"
    secure: starttls
    username: "{{ _email_address }}"
    password: "{{ _email_password }}"
    subject: Ansible-report {{ ansible_hostname }}
    body: "Ansible facts on host {{ ansible_hostname }} in attachment ansible_facts.txt."
    from: "{{ _email_address }}"
    to: "{{ _email_address }}"
    attach: "/tmp/ansible_facts.txt"
    headers: "Reply-To={{ _email_address }}"
    charset: us-ascii
