---

- name: "include ansible secrets to get emailpassword."
  include_vars: inventory/group_vars/vault.yaml

- name: "Configure /etc/ssmtp/ssmtp.conf."
  lineinfile:
    dest: '/etc/ssmtp/ssmtp.conf'
    regexp: "^{{ item.regexp }}"
    state: present
    insertafter: '^#\s*{{ item.insertafter }}'
    line: "{{ item.line }}"
  with_items:
    - { regexp: 'mailhub=',          insertafter: 'mailhub=',           line: 'mailhub={{ _mail_hubhost }}:{{ _mail_hubport }}'  }
    - { regexp: 'AuthUser=',         insertafter: 'AuthUser=',          line: "AuthUser={{ _mail_address }}"                     }
    - { regexp: 'AuthPass=',         insertafter: 'AuthPass=',          line: "AuthPass={{ _mail_password }}"                    }
    - { regexp: 'FromLineOverride=', insertafter: 'FromLineOverride=',  line: 'FromLineOverride=YES'                             }
    - { regexp: 'UseSTARTTLS=',      insertafter: 'UseSTARTTLS=',       line: 'UseSTARTTLS=YES'                                  }
    - { regexp: 'UseTLS=',           insertafter: 'UseTLS=',            line: 'UseTLS=YES'                                       }
    - { regexp: 'RewriteDomain=',    insertafter: 'RewriteDomain=',     line: 'RewriteDomain=gmail.com'                          }
    - { regexp: 'Hostname=',         insertafter: 'Hostname=',          line: 'Hostname=localhost'                               }
    - { regexp: 'TLS_CA_File=',      insertafter: 'TLS_CA_File=',       line: "TLS_CA_File={{ _tls_ca_file }}"                   }
  become: true

- name: "Write Ansible facts to /tmp/ansible_facts.txt"
  copy: 
    content: "{{ ansible_facts }}" 
    dest: "/tmp/ansible_facts.txt"
  become: true

- name: "Send test e-mail from {{ ansible_hostname }} to {{ _mail_address }}, attaching ansible facts."
  mail:
    host: "{{ _mail_hubhost }}"
    port: "{{ _mail_hubport }}"
    secure: starttls
    username: "{{ _mail_address }}"
    password: "{{ _mail_password }}"
    subject: Ansible-report {{ ansible_hostname }}
    body: "Ansible facts on host {{ ansible_hostname }} in attachment ansible_facts.txt."
    from: "{{ _mail_address }}"
    to: "{{ _mail_address }}"
    attach: "/tmp/ansible_facts.txt"
    headers: "Reply-To={{ _mail_address }}"
    charset: us-ascii
