---
# tasks file for baseline

- include: localesettings.yml

- include: aliasses.yml
  loop: "{{ _accounts }}"

- include: cronjobs.yml
  when: _wants_crontab|bool == true

- include: git.yml
  when: _wants_git|bool == true
  loop: "{{ _accounts }}"

- include: hosts.yml
    
- include: motd.yml
  loop: "{{ _accounts }}"

- include: prompt.yml
  loop: "{{ _accounts }}"

- include: timezone.yml

- include: tmux.yml
  loop: "{{ _accounts }}"

- include: vimsettings.yml
  loop: "{{ _accounts }}"

- include: ansible.yml
  when: _wants_ansible|bool == true
  loop: "{{ _accounts }}"
    
- include: mail.yml

- include: motd.yml
  loop: "{{ _accounts }}"

- include: raspi-config.yml
  when: "'raspberry' in _host_type"

- include: sshagent.yml
  when: _wants_sshagent|bool == true
  loop: "{{ _accounts }}"

