---

- name: "get home directory {{item}}"
  getent:
    database: passwd
    key: "{{item}}"
    split: ":"

- set_fact:
    _home_directory: "{{getent_passwd[item][4]}}"

- name: "copies motd.sh to {{_home_directory}}/.motd.sh"
  copy:
    src: 'files/motd.sh'
    dest: '{{_home_directory}}/.motd.sh'
    owner: "{{item}}"
    group: "{{item}}"
    mode: 0755
  become: true

- name: "add .motd.sh to {{_home_directory}}/.bashrc"
  lineinfile:
    path: "{{_home_directory}}/.bashrc"
    regexp: '^{{_home_directory}}/.motd.sh'
    line: {{_home_directory}}/.motd.sh
    owner: "{{item}}"
    group: "{{item}}"
    mode: '0644'


