---
# These task will install basic packages.



# http://docs.ansible.com/ansible/apt_module.html
- name: "apt install basic packages."
  apt: 
    name: "{{ packages }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 3600
  vars:
    packages:
    - apt-utils 
    - cron 
    - curl
    - git 
    - mailutils
    - netcat 
    - net-tools 
    - podman
    - rsync
    - ssmtp
    - tmux
    - vim
    - wget
  become: true

- name: "apt update: refresh cache."
  apt: 
    update_cache: yes
  become: true

- name: "apt upgrade: update all packages to the latest version."
  apt: 
    upgrade: full
  become: true
