---
# These task will install basic packages.

# http://docs.ansible.com/ansible/apt_module.html

- name: create podman repo
  copy:
    content: 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Raspbian_10/ /'
    dest: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
    owner: root
    group: root
    mode: 0644
  become: true

- name: Get gpg key
  shell: |
    curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Raspbian_10/Release.key | sudo apt-key add -

- name: "apt update: refresh cache."
  apt: 
    update_cache: yes
  become: true

- name: "apt install basic packages."
  apt: 
    name: "{{ packages }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 3600
  vars:
    packages:
    - apt-utils 
    - cron 
    - curl
    - git 
    - jq
    - mailutils
    - netcat 
    - net-tools 
    - podman
    - rsync
    - ssmtp
    - tmux
    - vim
    - wget
  become: true

- name: "apt update: refresh cache."
  apt: 
    update_cache: yes
  become: true

- name: "apt upgrade: update all packages to the latest version."
  apt: 
    upgrade: full
  become: true
