---

- name: "Get home directory {{ item }}."
  shell: >
    getent passwd {{ item }} | cut -d: -f6
  changed_when: false
  register: user_home

- name: "Clone https://github.com/tedsluis/bash-git-prompt.git to {{ user_home.stdout }}/.bash-git-prompt"
  git:
    repo: https://github.com/tedsluis/bash-git-prompt.git
    dest: "{{ user_home.stdout }}/.bash-git-prompt"
    depth: 1
    force: yes
  become: true

- name: set permissions on files
  file:
    path: "{{ user_home.stdout }}/.bash-git-prompt"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0774
    recurse: true
  become: true
  
- name: "Copies .git-prompt-colors.sh to {{ user_home.stdout }}/.git-prompt-colors.sh"
  copy:
    src: 'files/.git-prompt-colors.sh'
    dest: "{{ user_home.stdout }}/.git-prompt-colors.sh"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0774
  become: true

- name: "Add git branch name to bash prompt using {{ user_home.stdout }}/.bashrc"
  blockinfile:
    dest: "{{ user_home.stdout }}/.bashrc"
    marker: "# {mark} -- ansible managed block bash prompt --"
    insertbefore: '^#\sBEGIN\s--\sansible\smanaged\sblock'
    block: |
      if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
         GIT_PROMPT_THEME=Custom
         GIT_PROMPT_THEME_FILE=~/.git-prompt-colors.sh
         GIT_PROMPT_ONLY_IN_REPO=1
         source $HOME/.bash-git-prompt/gitprompt.sh
      fi
  become: true
