---

- name: "get home directory {{item}}"
  getent:
    database: passwd
    key: "{{item}}"
    split: ":"

- set_fact:
    _home_directory: "{{getent_passwd[item][4]}}"

- name: "Clone https://github.com/tedsluis/bash-git-prompt.git to {{ _home_directory }}/.bash-git-prompt"
  git:
    repo: https://github.com/tedsluis/bash-git-prompt.git
    dest: "{{ _home_directory }}/.bash-git-prompt"
    depth: 1
    force: yes
  become: true

- name: set permissions on files
  file:
    path: "{{ _home_directory }}/.bash-git-prompt"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0774
    recurse: true
  become: true
  
- name: "Copies .git-prompt-colors.sh to {{ _home_directory }}/.git-prompt-colors.sh"
  copy:
    src: 'files/.git-prompt-colors.sh'
    dest: "{{ _home_directory }}/.git-prompt-colors.sh"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0774
  become: true

- name: "Add git branch name to bash prompt using {{ _home_directory }}/.bashrc"
  blockinfile:
    dest: "{{ _home_directory }}/.bashrc"
    marker: "# {mark} -- ansible managed block bash prompt --"
    insertbefore: '^#\sBEGIN\s--\sansible\smanaged\sblock'
    block: |
      if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
         GIT_PROMPT_THEME=Custom
         GIT_PROMPT_THEME_FILE=~/.git-prompt-colors.sh
         GIT_PROMPT_ONLY_IN_REPO=1
         source $HOME/.bash-git-prompt/gitprompt.sh
      fi
  become: true
