---

- name: stop cockcpit.socket
  systemd:
    name: cockpit.socket
    state: stopped
    enabled: no
    masked: yes
  become: true
  failed_when: false

- name: stop cockcpit
  systemd:
    name: cockpit
    state: stopped
    enabled: no
    masked: yes
  become: true
  failed_when: false
