---

- name: "get home directory {{item}}"
  getent:
    database: passwd
    key: "{{item}}"
    split: ":"

- set_fact:
    _home_directory: "{{getent_passwd[item][4]}}"

- name: "insert ssh-agent in to {{ _home_directory }}/.bashrc"
  become: true
  blockinfile:
    create: true
    insertbefore: '^#\sBEGIN\s--\sansible\smanaged\sblock\stmux\s--'
    dest: "{{ _home_directory }}/.bashrc"
    marker: "# {mark} -- ansible managed block ssh-agent --"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0664
    block: |
      function start_agent {
           echo "Initialising new SSH agent..."
           eval "$(ssh-agent -s -t 86400)"
           echo "export SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" > ~/.ssh/agentsock
           chmod +x ~/.ssh/agentsock
           echo "export SSH_AGENT_PID=${SSH_AGENT_PID}" > ~/.ssh/agentpid
           chmod +x ~/.ssh/agentpid
           echo succeeded
           /usr/bin/ssh-add $HOME/.ssh/id_rsa;
      } # Source SSH settings, if applicable
      if [ -z $TMUX ];then
           if [[ $(ps aux | grep ssh-agent | grep -v grep | grep -c {{item}}) == "0" ]];then
                start_agent;
           else
         .      ~/.ssh/agentsock
       .        ~/.ssh/agentpid
           fi
      fi
      if [[ $(ssh-add -l) =~ "The agent has no identities" ]];then
           /usr/bin/ssh-add $HOME/.ssh/id_rsa
      fi
      alias ssh='eval $(tmux show-env | /usr/bin/grep "^SSH_AGENT\|^SSH_AUTH_SOCK") && ssh'
  when: '"root" not in _home_directory'

