---

- name: "include Ansible secrets to get rsa keys."
  include_vars: group_vars/vault.yaml

- name: "get home directory {{ item }}."
  shell: >
    getent passwd {{ item }} | cut -d: -f6
  changed_when: false
  register: user_home

- name: "create {{ user_home.stdout }}/.ssh directory"
  file:
    path: "{{ user_home.stdout }}/.ssh"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0700
  become: true

- name: "create {{ user_home.stdout }}/.ssh/id_rsa"
  copy:
    content: "{{ id_rsa }}"
    #dest: "/tmp/id_rsa"
    dest: "{{ user_home.stdout}}/.ssh/id_rsa"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0400
  become: true
  when: _wants_private_key|bool == true

- name: "create {{ user_home.stdout }}/.ssh/id_rsa.pub"
  copy:
    content: "{{ id_rsa_pub }}"
    dest: "{{ user_home.stdout}}/.ssh/id_rsa.pub"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
  become: true

- name: "create {{ user_home.stdout }}/.ssh/authorized_keys"
  copy:
    content: "{{ id_rsa_pub }}"
    dest: "{{ user_home.stdout}}/.ssh/authorized_keys"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
  become: true

- name: "create {{ user_home.stdout }}/.ssh/cofig"
  file:
    path: "{{ user_home.stdout }}/.ssh/config"
    state: touch
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0744
  become: true

- name: "configure {{ user_home.stdout }}/.ssh/cofig"
  become: true
  when: _wants_private_key|bool == true
  blockinfile:
    create: true
    dest: "{{ user_home.stdout }}/.ssh/config"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0744
    block: |
      Host github.com
          Hostname github.com
          User tedsluis
          IdentityFile ~/.ssh/id_rsa


