---

- name: "get home directory {{item}}"
  getent:
    database: passwd
    key: "{{item}}"
    split: ":"

- set_fact:
    _home_directory: "{{getent_passwd[item][4]}}"

- name: "copies tmux.conf to {{ _home_directory }}/.tmux.conf"
  copy:
    src: 'files/tmux.conf'
    dest: "{{ _home_directory }}/.tmux.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0775
  become: true

- name: "insert tmux in to {{ _home_directory }}/.bashrc"
  become: true
  blockinfile:
    create: true
    dest: "{{ _home_directory }}/.bashrc"
    marker: "# {mark} -- ansible managed block tmux --"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0664
    block: |
      if [[ ! "$TERM" =~ "screen" ]]; then
           tmux a  || tmux 
      fi
  when: '"root" not in _home_directory'

