# tmux configuration

# Get home directory
- name: "Get home directory {{ item }}."
  shell: >
    getent passwd {{ item }} | cut -d: -f6
  changed_when: false
  register: user_home

# http://docs.ansible.com/ansible/copy_module.html
# Copies tmux.conf to ~/.tmux.conf
- name: "Copies tmux.conf to {{ user_home.stdout }}/.tmux.conf"
  copy:
    src: 'files/tmux.conf'
    dest: "{{ user_home.stdout }}/.tmux.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0775
  become: true

- name: "Get home directory {{ item }}."
  shell: >
    getent passwd {{ item }} | cut -d: -f6
  changed_when: false
  register: user_home

- name: "insert tmux in to {{ user_home.stdout }}/.bashrc"
  become: true
  blockinfile:
    create: true
    dest: "{{ user_home.stdout }}/.bashrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0775
    block: |
      if [[ ! "$TERM" =~ "screen" ]]; then
           tmux attach -t default || tmux new -s default
      fi
  when: '"root" not in user_home.stdout'

