# tmux configuration

- name: "get home directory {{ item }}."
  shell: >
    getent passwd {{ item }} | cut -d: -f6
  changed_when: false
  register: user_home

- name: "copies tmux.conf to {{ user_home.stdout }}/.tmux.conf"
  copy:
    src: 'files/tmux.conf'
    dest: "{{ user_home.stdout }}/.tmux.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0775
  become: true

- name: "insert tmux in to {{ user_home.stdout }}/.bashrc"
  become: true
  blockinfile:
    create: true
    dest: "{{ user_home.stdout }}/.bashrc"
    marker: "# {mark} -- ansible managed block tmux --"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 775
    block: |
      if [[ ! "$TERM" =~ "screen" ]]; then
           tmux attach -t default || tmux new -s default
      fi
  when: '"root" not in user_home.stdout'

