# tmux configuration

# Get home directory
- name: "Get home directory {{ item }}."
  shell: >
    getent passwd {{ item }} | cut -d: -f6
  changed_when: false
  register: user_home

# http://docs.ansible.com/ansible/copy_module.html
# Copies tmux.conf to ~/.tmux.conf
- name: "Copies tmux.conf to {{ user_home.stdout }}/.tmux.conf"
  copy:
    src: 'files/tmux.conf'
    dest: "{{ user_home.stdout }}/.tmux.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0775
  become: true

- name: "Get home directory {{ item }}."
  shell: >
    getent passwd {{ item }} | cut -d: -f6
  changed_when: false
  register: user_home

- name: Insert tmux into .bashrc
  lineinfile:
    dest: "{{ user_home.stdout }}/.bashrc"
    regexp: '^tmux'
    state: present
    line: 'tmux list-sessions'
  when: '"root" not in user_home.stdout'
  become: true

