---
# These task will do the vim configuration.

# http://docs.ansible.com/ansible/lineinfile_module.html

# Set vim syntax highlighting on (debian based hosts)
- name: "Set vim syntax no (globaly) in /etc/vim/vimrc."
  lineinfile:
    dest: /etc/vim/vimrc
    regexp: '^\s*"?syntax o'
    state: present
    line: 'syntax on'
  become: true
