---
# These task will do the vim configuration.

# http://docs.ansible.com/ansible/lineinfile_module.html

# Set vim syntax highlighting 
- name: "Set vim syntax no (globaly) in {{ _etc_vimrc }}"
  lineinfile:
    dest: "{{ _etc_vimrc }}"
    regexp: '^\s*"?syntax o'
    state: present
    line: 'syntax on'
  become: true

