---
# These task will do the vim configuration.

- name: "set vim syntax no (globaly) in {{ _etc_vimrc }}"
  lineinfile:
    dest: "{{ _etc_vimrc }}"
    regexp: '^\s*"?syntax o'
    state: present
    line: 'syntax on'
  become: true

