---

- name: restart mongo
  systemd:
    daemon_reload: yes
    state: restarted
    name: mongo

- name: restart rocketchat
  systemd:
    daemon_reload: yes
    state: restarted
    name: rocketchat


