---

- name: reload daemon mongo
  systemd:
    daemon_reload: yes
    name: mongo
  become: true

- name: restart mongo
  systemd:
    daemon_reload: yes
    state: restarted
    name: mongo
  become: true

- name: reload daemon rocketchat
  systemd:
    daemon_reload: yes
    name: rocketchat
  become: true

- name: restart rocketchat
  systemd:
    state: restarted
    name: rocketchat
  become: true


