---

- name: "include ansible secrets to get duckdns token"
  include_vars: inventory/group_vars/vault.yaml

- name: create grafana directories
  file:
    path: "{{item.directory}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
    state: directory
  become: true
  with_items:
    - { directory: "/var/lib/grafana"                             ,owner: "grafana" ,group: "grafana" ,mode: "0777" }
    - { directory: "/var/lib/grafana/etc"                         ,owner: "grafana" ,group: "grafana" ,mode: "0777" }
    - { directory: "/var/lib/grafana/etc/certs"                   ,owner: "grafana" ,group: "grafana" ,mode: "0777" }
    - { directory: "/var/lib/grafana/etc/dashboards"              ,owner: "grafana" ,group: "grafana" ,mode: "0777" }
    - { directory: "/var/lib/grafana/etc/provisioning"            ,owner: "grafana" ,group: "grafana" ,mode: "0777" }
    - { directory: "/var/lib/grafana/etc/provisioning/dashboards" ,owner: "grafana" ,group: "grafana" ,mode: "0777" }
    - { directory: "/var/lib/grafana/etc/provisioning/datasources",owner: "grafana" ,group: "grafana" ,mode: "0777" }
    - { directory: "/var/lib/grafana/etc/provisioning/notifiers"  ,owner: "grafana" ,group: "grafana" ,mode: "0777" }
    - { directory: "/var/lib/grafana/etc/provisioning/plugins"    ,owner: "grafana" ,group: "grafana" ,mode: "0777" }
    - { directory: "/var/lib/grafana/lib"                         ,owner: "grafana" ,group: "grafana" ,mode: "0777" }
    - { directory: "/var/lib/grafana/usr"                         ,owner: "grafana" ,group: "grafana" ,mode: "0777" }

- name: "pull docker.io/grafana/grafana:{{_grafana_image_tag}} image"
  shell: |
    podman pull docker.io/grafana/grafana:{{_grafana_image_tag}}
  register: _image_pull
  become: true

- debug:
    var: _image_pull

- name: create local /tmp/grafana directory for certs
  file:
    path: /tmp/grafana
    owner: root
    group: root
    mode: 0777
    state: directory
  delegate_to: localhost
  become: true

- name: fetch keys from /var/lib/letsencrypt/keys/letsencrypt/
  delegate_to: "{{_letsencrypt_hostname}}"
  run_once: yes
  fetch:
    src: "/var/lib/letsencrypt/keys/letsencrypt/{{item}}"
    dest: "/tmp/grafana/"
    flat: yes
  become: true
  with_items:
    - privkey.pem
    - fullchain.pem

- name: place cert
  copy:
    src: /tmp/grafana/fullchain.pem
    dest: /var/lib/grafana/etc/certs/fullchain.pem
    owner: grafana
    group: grafana
    mode: 0664
  become: true

- name: place key
  copy:
    src: /tmp/grafana/privkey.pem
    dest: /var/lib/grafana/etc/certs/privkey.pem
    owner: grafana
    group: grafana
    mode: 0664
  become: true

- name: create /var/lib/grafana/etc/grafana.ini
  template:
    src: grafana.ini.j2
    dest: /var/lib/grafana/etc/grafana.ini
    owner: grafana
    group: grafana
    mode: 0666
  become: true
  notify: _restart_grafana

- name: create /var/lib/grafana/etc/dashboards/dashboard.*.json
  copy:
    src: "{{item}}"
    dest: "/var/lib/grafana/etc/dashboards/{{item}}"
    owner: grafana
    group: grafana
    mode: 0666
  become: true
  with_items:
    - dashboard.1.json
    - dashboard.2.json
  notify: _restart_grafana

- name: create /var/lib/grafana/etc/provisioning/datasources/datasource.aa.yaml
  template:
    src: datasource.aa.yaml.j2
    dest: /var/lib/grafana/etc/provisioning/datasources/datasource.aa.yaml
    owner: grafana
    group: grafana
    mode: 0666
  become: true
  notify: _restart_grafana

- name: create /var/lib/grafana/etc/provisioning/dashboards/dashboard.*.yaml
  copy:
    src: "{{item}}"
    dest: "/var/lib/grafana/etc/provisioning/dashboards/{{item}}"
    owner: grafana
    group: grafana
    mode: 0666
  become: true
  with_items: 
    - dashboard.1.yaml
    - dashboard.2.yaml
  notify: _restart_grafana

- name: create /etc/systemd/system/grafana.service
  template:
    src: grafana.service.j2
    dest: /etc/systemd/system/grafana.service
    owner: root
    group: root
    mode: 0664
  register: _service
  become: true
  notify: _restart_grafana

- name: start and enable grafana.service
  systemd:
    name: grafana
    state: started
    enabled: true
  become: true

- name: grafana container state
  shell: |
    podman ps -a --format "{{ '{{' }}.Status{{ '}}' }}  {{ '{{' }}.Names{{ '}}' }}  {{ '{{' }}.ID{{ '}}' }}" --filter 'name=grafana'
  register: _container_state
  become: true

- debug:
    var: _container_state

- name: trigger handelers
  meta: flush_handlers

- name: "pause until grafana is reachable"
  uri:
    url: "https://{{_grafana_url}}:3000/login"
    follow_redirects: none
    method: GET
  register: _result
  until: _result.status == 200
  retries: 60 # 60 * 5 seconds = 5 minutes
  delay: 5 # Every 5 seconds

- name: set grafana password
  shell: |
    podman exec grafana /usr/share/grafana/bin/grafana-cli admin reset-admin-password {{_grafana_admin_password}} --config=/etc/grafana/grafana.ini || echo "set password failed."
  become: true
  register: _set_grafana_password

- debug:
    var: _set_grafana_password

