#!/usr/bin/env ansible-playbook

- name: alertmanager

  hosts:
    - fed160

  vars:
    ansible_user: ansible

  roles:
  - packages
  - users-and-groups
  - firewall
  - role: dnsmasq
    when: _wants_dnsmasq|bool == true
  - role: alertmanager
    when: "'alertmanager' in group_names"

