---

- name: create kubernetes repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: 0664
    owner: root
    group: root
  become: true
  when: "'kubernetes' in group_names"

- name: dnf module enable cri-o:1.20
  shell: |
    sudo dnf module enable cri-o:1.20 -y
  when: "'kubernetes' in group_names"

- name: define _packages
  set_fact:
    _packages: []

- debug:
    msg: "{{_packages+lookup('vars',item)}}"
  with_items: "{{ lookup('varnames', '.+_packages$').split(',') }}"

- name: add _*_packages
  set_fact:
    _packages: "{{(_packages+lookup('vars',item))|unique}}"
  with_items: "{{ lookup('varnames', '.+_packages$').split(',') }}"

- name: show packages 
  debug:
    msg: "PACKAGE={{item}}"
  with_items: "{{_packages}}"

- name: "install packages"
  dnf:
    name: "{{_packages}}"
    state: present
  become: true
