---

- name: define _packages
  set_fact:
    _packages: []

- debug:
    msg: "{{_packages+lookup('vars',item)}}"
  with_items: "{{ lookup('varnames', '.+_packages$').split(',') }}"

- name: add _*_packages
  set_fact:
    _packages: "{{(_packages+lookup('vars',item))|unique}}"
  with_items: "{{ lookup('varnames', '.+_packages$').split(',') }}"

- name: show packages 
  debug:
    msg: "PACKAGE={{item}}"
  with_items: "{{_packages}}"

- name: "install packages"
  dnf:
    name: "{{_packages}}"
    state: present
  become: true
