---

- name: stop letsencrypt-swag.service
  listen: _restart_letsencrypt_swag
  systemd:
    name: letsencrypt-swag
    state: stopped
  become: true
  
- name: daemon reload letsencrypt-swag.service
  listen: _restart_letsencrypt_swag
  systemd:
    name: letsencrypt-swag
    state: stopped
    daemon_reload: true
  become: true

- name: start letsencrypt-swag.service
  listen: _restart_letsencrypt_swag
  systemd:
    name: letsencrypt-swag
    state: started
  become: true

---

- name: stop httpd-<sitename>.service
  listen: _restart_httpd
  systemd:
    name: "httpd-{{item.sitename}}"
    state: stopped
  with_items: "{{_httpd_sites}}"
  become: true
  
- name: daemon reload httpd-<sitename>.service
  listen: _restart_httpd
  systemd:
    name: "httpd-{{item.sitename}}"
    state: stopped
    daemon_reload: true
  with_items: "{{_httpd_sites}}"
  become: true

- name: start httpd-<sitename>.service
  listen: _restart_httpd
  systemd:
    name: "httpd-{{item.sitename}}"
    state: started
  with_items: "{{_httpd_sites}}"
  become: true

