---

- name: create raspberryfan directories
  file:
    path: "{{item.directory}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
    state: directory
  become: true
  with_items:
    - { directory: "/var/lib/raspberryfan", owner: "root" ,group: "root" ,mode: "0774" }

- include_role:
    name: pull-images
  vars:
    _images:
      - _raspberryfan_image
    
- name: create /etc/systemd/system/raspberryfan.service
  template:
    src: raspberryfan.service.j2
    dest: /etc/systemd/system/raspberryfan.service
    owner: root
    group: root
    mode: 0664
  become: true
  notify: _restart_raspberryfan

- name: start and enable raspberryfan.service
  systemd:
    name: raspberryfan
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: raspberryfan container state
  shell: |
    podman ps -a --format "{{ '{{' }}.Status{{ '}}' }}  {{ '{{' }}.Names{{ '}}' }}  {{ '{{' }}.ID{{ '}}' }}" --filter 'name=raspberryfan'
  register: _raspberryfan_state
  become: true

- debug:
    var: _raspberryfan_state

- name: trigger handelers
  meta: flush_handlers
