_hostname: fed143
_ip_address: '192.168.11.143'

_httpd_sites:
  - {sitename: 'test', url: 'fed143.bachstraat20.duckdns.org', http_port: '30080', https_port: '30443' }
  - {sitename: 'dev',  url: 'fed143.bachstraat20.duckdns.org', http_port: '31080', https_port: '31443' }



