---
- name: Authenticate with Docker registry if registry password given
  shell: |
    podman login {{ docker_registry }} --username {{ docker_registry_username }}  --password {{ docker_registry_password }}
    #  docker_login:
    #    registry: "{{ docker_registry }}"
    #    username: "{{ docker_registry_username }}"
    #    password: "{{ docker_registry_password }}"
    #    reauthorize: true
  when: docker_registry is defined and docker_registry_password is defined
  delegate_to: localhost

- name: Remove local images to ensure proper push behavior
  block:
    - name: Remove awx image
      shell: |
        podman rmi {{ docker_registry }}/{{ docker_registry_repository }}/{{ awx_image }}:{{ awx_version }} 2> /dev/null || echo "gone.."
        #   docker_image:
        #     name: "{{ docker_registry }}/{{ docker_registry_repository }}/{{ awx_image }}"
        #     tag: "{{ awx_version }}"
        #     state: absent
  delegate_to: localhost

- name: Tag and Push Container Images
  block:
    - name: Tag and push awx image to registry
      shell: |
        podman tag {{ awx_image }}:{{item}} {{ docker_registry }}/{{ docker_registry_repository }}/{{ awx_image }}:{{item}}
        podman push {{ docker_registry }}/{{ docker_registry_repository }}/{{ awx_image }}:{{item}}
        #  docker_image:
        #    name: "{{ awx_image }}"
        #    repository: "{{ docker_registry }}/{{ docker_registry_repository }}/{{ awx_image }}"
        #    tag: "{{ item }}"
        #    push: true
      with_items:
        - "latest"
        - "{{ awx_version }}"
      register: _result
      until: _result.rc == 0
      retries: 10 # 10 * 10 seconds = 5 minutes
      delay: 10 # E
  delegate_to: localhost

- name: Set full image path for Registry
  set_fact:
    awx_docker_actual_image: >-
      {{ docker_registry }}/{{ docker_registry_repository }}/{{ awx_image }}:{{ awx_version }}
