---
- set_fact:
    _image: "{{outer_item}}"
    _archs: "{{_manifest[outer_item]}}"

- debug:
    msg: "IMAGE:{{_image}}, ARCHS{{_archs}}"

- name: check if manifest exists
  shell: |
    podman manifest exists "{{_image_registry_url}}{{_image}}"
    echo "EXISTS=$?"
  become: true
  register: _manifest_exists

- debug:
    msg: "{{_manifest_exists}}"

- name: create manifest
  shell: |
    podman manifest create "{{_image_registry_url}}{{_image}}"
  become: true
  when: "'EXISTS=1' in  _manifest_exists.stdout"

- name: add image to manifest
  shell: 
    podman manifest add --arch {{item}} "{{_image_registry_url}}{{_image}}"  "{{_image_registry_url}}{{_image}}-{{item}}"
  loop: "{{_archs}}"
  become: true

- name: "push manifest {{_image_registry_url}}{{_image}}"
  shell: |
    podman manifest push {{_image_registry_url}}{{_image}} {{_image_registry_url}}{{_image}}
  become: true