---

- debug:
    msg: "EXT:{{outer_item.ext}}, IMAGE:{{outer_item.image}}, ARCH:{{outer_item.arch}}"

- name: set external and internal
  set_fact:
    _internal:  "{{_image_registry_url}}{{outer_item.image}}-{{outer_item.arch}}"
    _external:  "{{outer_item.ext}}{{outer_item.image}}"

- name: pull image {{_external}}
  shell: |
    podman pull --arch {{outer_item.arch}} --os linux {{_external}}
  become: true
  register: _image_pulled

- debug:
    var: _image_pulled

- name: tag {{_external}} {{_internal}}
  shell: |
    podman tag {{_external}} {{_internal}}
  become: true

- name: push image {{_external}} to {{_internal}}
  shell: |
    podman login -u registry -p "{{hostvars[groups['registry'][0]]['_registry_password']}}" "{{_image_registry_url}}"
    podman push {{_internal}}
  become: true
  register: _image_pushed

- debug:
    var: _image_pushed





