---

- debug:
    msg: "EXT:{{item.ext}}, IMAGE:{{item.image}}, ARCH:{{item.arch}}"

- name: set external and internal
  set_fact:
    _internal:  "{{_image_registry_url}}{{item.image}}-{{item.arch}}"
    _external:  "{{item.ext}}{{item.image}}"
    _pullhost: "{{_pull_host[item.arch]}}"

- name: pull image {{_external}}
  delegate_to: "{{_pullhost}}"
  podman_image:
    pull: true
    force: true
    name: "{{_external}}"
  become: true
  register: _image_pulled

- debug:
    var: _image_pulled

- name: tag {{_external}} {{_internal}}
  delegate_to: "{{_pullhost}}"
  shell: |
    podman tag {{_external}} {{_internal}}
  become: true

- name: push image {{_external}} to {{_internal}}
  delegate_to: "{{_pullhost}}"
  shell: |
    podman login -u registry -p "{{hostvars[groups['registry'][0]]['_registry_password']}}" "{{_image_registry_url}}"
    podman push {{_internal}}
  become: true
  register: _image_pushed

- debug:
    var: _image_pushed





