---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: roles/kubernetes/files/argocd/apps/
    targetRevision: HEAD
    repoURL: https://github.com/tedsluis/ansible-playbooks.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

