{
 "title": "Prometheus Alertmanager Karma",
 "time": { "from": "2021-01-03T08:06:17.218Z", "to": "2021-01-03T09:33:08.492Z" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "label_values(ALERTS, job)" },
   { "name": "severity", "label": "severity", "query": "label_values(ALERTS, severity)" },
   { "name": "instance", "label": "instance", "query": "label_values(ALERTS, instance)" },
   {
    "name": "alertstate",
    "label": "alertstate",
    "query": "label_values(ALERTS, alertstate)"
   },
   {
    "name": "alertname",
    "label": "alertname",
    "query": "label_values(ALERTS, alertname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Prometheus Alerts count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{severity=~\"$severity\",alertname=~\"$alertname\", alertstate=~\"$alertstate\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{severity}}: {{alertname}} {{alertstate}} {{instance}} {{job}}"
    }
   ]
  },
  {
   "title": "Prometheus targerts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_sd_discovered_targets{config=\"blackbox-200\", name=\"scrape\"}",
     "legendFormat": "blackbox-200"
    },
    {
     "expr": "prometheus_sd_discovered_targets{config=\"blackbox-200-auth\", name=\"scrape\"}",
     "legendFormat": "blackbox-200-auth"
    },
    {
     "expr": "prometheus_sd_discovered_targets{config=\"blackbox-nodeexporter-200\", name=\"scrape\"}",
     "legendFormat": "blackbox-nodeexporter"
    },
    {
     "expr": "prometheus_sd_discovered_targets{config=\"blackbox-nodeexporter-dns_test\", name=\"scrape\"}",
     "legendFormat": "blackbox-dns"
    },
    {
     "expr": "prometheus_sd_discovered_targets{config=\"config-0\", name=\"notify\"}",
     "legendFormat": "config-0"
    },
    {
     "expr": "prometheus_sd_discovered_targets{config=\"karma\", name=\"scrape\"}",
     "legendFormat": "karma"
    },
    {
     "expr": "prometheus_sd_discovered_targets{config=\"node_exporters_https\", name=\"scrape\"}",
     "legendFormat": "nodeexporter"
    },
    {
     "expr": "prometheus_sd_discovered_targets{config=\"node_exporters_postgres\", name=\"scrape\"}",
     "legendFormat": "postgres"
    },
    {
     "expr": "prometheus_sd_discovered_targets{config=\"prometheus\", name=\"scrape\"}",
     "legendFormat": "prometheus"
    },
    {
     "expr": "prometheus_sd_discovered_targets{config=\"snmp\", name=\"scrape\"}",
     "legendFormat": "snmp"
    },
    {
     "expr": "prometheus_sd_discovered_targets{config=\"tower\", name=\"scrape\"}",
     "legendFormat": "tower"
    }
   ]
  },
  {
   "title": "Karma alert count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "karma_collected_alerts_count{state='active'}",
     "legendFormat": "active"
    },
    {
     "expr": "karma_collected_alerts_count{state='suppressed'}",
     "legendFormat": "suppressed"
    },
    {
     "expr": "karma_collected_alerts_count{state='unprocessed'}",
     "legendFormat": "unprocessed"
    }
   ]
  }
 ]
}