{
 "title": "New dashboard Copy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_exporter_build_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "cpu load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:9100\"}",
     "legendFormat": "{{instance}}:cpu load"
    }
   ]
  },
  {
   "title": "cpu temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "raspberry_fan_temp{instance=~'$node:9100'}",
     "legendFormat": "{{instance}}:temp (c)"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "raspberry_fan_speed{instance=~'$node:9100'}",
     "legendFormat": "{{instance}}:speed (%)"
    }
   ]
  }
 ]
}