{
 "title": "dump1090exporter",
 "description": "This dashboard displays dump1090 metrics that get exposed to Prometheus by the dump1090exporter.",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Aircraft Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "repeat": "node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_observed{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}"
    }
   ]
  },
  {
   "title": "Aircraft w/ Position",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "repeat": "node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_with_position{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}"
    }
   ]
  },
  {
   "title": "Max Range",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "repeat": "node",
   "format": "lengthm",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_max_range{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\"}"
    }
   ]
  },
  {
   "title": "Messages/Sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "repeat": "node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(dump1090_messages_total{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}[1m])"
    }
   ]
  },
  {
   "title": "Signal Peak",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "repeat": "node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_stats_local_peak_signal_strength_dbFS{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}"
    }
   ]
  },
  {
   "title": "Signal Mean",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "repeat": "node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_stats_local_signal_strength_dbFS{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}"
    }
   ]
  },
  {
   "title": "Aircraft Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_observed{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}"
    }
   ]
  },
  {
   "title": "Aircraft w/ Position",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_with_position{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}"
    }
   ]
  },
  {
   "title": "Max Range",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "format": "lengthm",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_max_range{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\"}"
    }
   ]
  },
  {
   "title": "Messages/Sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(dump1090_messages_total{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}[1m])"
    }
   ]
  },
  {
   "title": "Signal Peak",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_stats_local_peak_signal_strength_dbFS{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}"
    }
   ]
  },
  {
   "title": "Signal Mean",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_stats_local_signal_strength_dbFS{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}"
    }
   ]
  },
  {
   "title": "Aircraft $node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_observed{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}",
     "legendFormat": "total"
    },
    {
     "expr": "dump1090_recent_aircraft_with_position{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}",
     "legendFormat": "W/ position"
    },
    {
     "expr": "dump1090_recent_aircraft_observed{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"} - dump1090_recent_aircraft_with_position{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}",
     "legendFormat": "Wo/ position"
    },
    {
     "expr": "dump1090_recent_aircraft_with_multilateration{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}",
     "legendFormat": "mlat"
    }
   ]
  },
  {
   "title": "Aircraft $node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_observed{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}",
     "legendFormat": "total"
    },
    {
     "expr": "dump1090_recent_aircraft_with_position{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}",
     "legendFormat": "W/ position"
    },
    {
     "expr": "dump1090_recent_aircraft_observed{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"} - dump1090_recent_aircraft_with_position{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}",
     "legendFormat": "Wo/ position"
    },
    {
     "expr": "dump1090_recent_aircraft_with_multilateration{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}",
     "legendFormat": "mlat"
    }
   ]
  },
  {
   "title": "Maximum Range $node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "repeat": "node",
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_max_range{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}",
     "legendFormat": "{{ time_period }}"
    }
   ]
  },
  {
   "title": "Maximum Range $node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_max_range{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}",
     "legendFormat": "{{ time_period }}"
    }
   ]
  },
  {
   "title": "messages / sec $node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dump1090_messages_total{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}[1m])",
     "legendFormat": "latest"
    },
    {
     "expr": "dump1090_stats_messages_total{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"} / 60",
     "legendFormat": "last1min"
    }
   ]
  },
  {
   "title": "messages / sec $node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dump1090_messages_total{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"latest\"}[1m])",
     "legendFormat": "latest"
    },
    {
     "expr": "dump1090_stats_messages_total{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"} / 60",
     "legendFormat": "last1min"
    }
   ]
  },
  {
   "title": "Signal Strength $node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "dbFS" }
   ],
   "targets": [
    {
     "expr": "dump1090_stats_local_signal_strength_dbFS{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}",
     "legendFormat": "mean"
    },
    {
     "expr": "dump1090_stats_local_peak_signal_strength_dbFS{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "dump1090_stats_local_noise_level_dbFS{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}",
     "legendFormat": "noise"
    }
   ]
  },
  {
   "title": "Signal Strength $node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "dbFS" }
   ],
   "targets": [
    {
     "expr": "dump1090_stats_local_signal_strength_dbFS{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}",
     "legendFormat": "mean"
    },
    {
     "expr": "dump1090_stats_local_peak_signal_strength_dbFS{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "dump1090_stats_local_noise_level_dbFS{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}",
     "legendFormat": "noise"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "repeat": "node",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "dump1090_stats_cpu_demod_milliseconds{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}",
     "legendFormat": "emod"
    },
    {
     "expr": "dump1090_stats_cpu_reader_milliseconds{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}",
     "legendFormat": "usb"
    },
    {
     "expr": "dump1090_stats_cpu_background_milliseconds{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "dump1090_stats_cpu_demod_milliseconds{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}",
     "legendFormat": "emod"
    },
    {
     "expr": "dump1090_stats_cpu_reader_milliseconds{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}",
     "legendFormat": "usb"
    },
    {
     "expr": "dump1090_stats_cpu_background_milliseconds{instance=\"$node.bachstraat20.duckdns.org:9105\",job=\"dump1090exporter\", time_period=\"last1min\"}",
     "legendFormat": "other"
    }
   ]
  }
 ]
}