---

- name: stop httpd.service
  listen: _restart_httpd
  systemd:
    name: httpd
    state: stopped
  become: true
  
- name: daemon reload httpd.service
  listen: _restart_httpd
  systemd:
    name: httpd
    state: stopped
    daemon_reload: true
  become: true

- name: start httpd.service
  listen: _restart_httpd
  systemd:
    name: httpd
    state: started
  become: true

