---

- name: create /etc/sssd/sssd.conf
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  become: true
  notify: _restart_sssd

- name: start and enable sssd and oddjobd
  systemd:
    name: "{{item}}"
    state: started
    enabled: true
  become: true
  with_items: 
    - sssd
    - oddjobd

- name: enable sssd authentication with home directory
  shell: |
    authconfig --enablesssd --enablesssdauth --enablelocauthorize --update
    authselect select sssd with-mkhomedir --force
  become: true

- name: trigger handelers
  meta: flush_handlers

