---

- name: stop gitea.service
  listen: _restart_gitea
  systemd:
    name: gitea
    state: stopped
  become: true
  
- name: daemon reload gitea.service
  listen: _restart_gitea
  systemd:
    name: gitea
    state: stopped
    daemon_reload: true
  become: true

- name: start gitea.service
  listen: _restart_gitea
  systemd:
    name: gitea
    state: started
  become: true


