---
# handlers file for restart gitea
- name: restart podman-compose
  shell: |
     podman-compose -f /etc/gitea/docker-compose.yml down
     podman-compose -f /etc/gitea/docker-compose.yml up -d
  become:true
