FROM {{_image_registry_url}}{{hostvars[groups['raspberryfan'][0]]['_fedora_image']['image']}}

RUN  dnf -y {% if _arch == "arm" %} --forcearch armv7hl {% endif %} update
RUN  dnf -y {% if _arch == "arm" %} --forcearch armv7hl {% endif %} install libgpiod-utils python3-libgpiod swig python2 python2-setuptools python-setuptools python-devel python3-devel python-setuptools python3-setuptools unzip curl wget make gcc which

RUN  mkdir -p /tmp; \
     wget https://github.com/joan2937/lg/archive/master.zip;  \
     unzip master.zip; \
     cd lg-master; \
     make; \
     make install

{% if ( ( _arch == "arm64" ) or ( _arch == "adm64" ) )  %}
RUN  cp /usr/local/lib/lib*gpio.so.1 /usr/lib64/
{% else %}
RUN  cp /usr/local/lib/liblgpio.so.1 /usr/lib/
{% endif %}

RUN if [ ! -e /usr/bin/python ]; then ln -s /usr/bin/python3 /usr/bin/python; fi

RUN  mkdir /src

COPY fan.py /src

RUN  mkdir -p /var/lib/node_exporter; \
     touch /var/lib/node_exporter/fan-metrics.prom

