---
- name: Copy the Node Exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

- name: Create textfile collector dir
  file:
    path: "{{ node_exporter_textfile_dir }}"
    state: directory
    owner: "{{ _node_exporter_system_user }}"
    group: "{{ _node_exporter_system_group }}"
    recurse: true
    mode: 0775
  when: node_exporter_textfile_dir | length > 0

- name: Create config dir
  file:
    path: /opt/node_exporter
    state: directory
    owner: "{{ _node_exporter_system_user }}"
    group: "{{ _node_exporter_system_group }}"
    recurse: true
    mode: 0775

- name: create local /root/tmp directory for certs
  file:
    path: /tmp/nodeexporter
    owner: root
    group: root
    mode: 0777
    state: directory
  delegate_to: localhost
  become: true

- name: fetch keys from /var/lib/letsencrypt/keys/letsencrypt/
  delegate_to: fed143
  run_once: yes
  fetch:
    src: "/var/lib/letsencrypt/keys/letsencrypt/{{item}}"
    dest: "/tmp/nodeexporter/"
    flat: yes
  become: true
  with_items:
    - privkey.pem
    - fullchain.pem

- name: place cert
  copy:
    src: /tmp/nodeexporter/fullchain.pem
    dest: /opt/node_exporter/node_exporter.crt
    owner: "{{ _node_exporter_system_user }}"
    group: "{{ _node_exporter_system_group }}"
  become: true

- name: place key
  copy:
    src: /tmp/nodeexporter/privkey.pem
    dest: /opt/node_exporter/node_exporter.key
    owner: "{{ _node_exporter_system_user }}"
    group: "{{ _node_exporter_system_group }}"
  become: true

- name: "include ansible secrets to get duckdns token"
  include_vars: inventory/group_vars/vault.yaml

- name: create configfile
  copy:
    content: |
      # ansible_managed
      tls_server_config:
        cert_file: /opt/node_exporter/node_exporter.crt
        key_file: /opt/node_exporter/node_exporter.key
      basic_auth_users:
        prometheus: "{{ _node_exporter_auth_pass_bcrypt_hashed }}"
    dest: /opt/node_exporter/web.yml
    owner: "{{ _node_exporter_system_user }}"
    group: "{{ _node_exporter_system_group }}"
  register: _config

- name: Allow Node Exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ node_exporter_web_listen_address.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
