---
- import_tasks: preflight.yml
  tags:
    - node_exporter_install
    - node_exporter_configure
    - node_exporter_run

- import_tasks: install.yml
  become: true
  when: (not __node_exporter_is_installed.stat.exists) or (__node_exporter_current_version_output.stderr_lines[0].split(" ")[2] != node_exporter_version)
  tags:
    - node_exporter_install

- import_tasks: selinux.yml
  become: true
  when: ansible_selinux.status == "enabled"
  tags:
    - node_exporter_configure

- import_tasks: configure.yml
  become: true
  tags:
    - node_exporter_configure

- name: Ensure Node Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: started
  tags:
    - node_exporter_run

- name: Ensure Node Exporter is restarted on config change
  become: true
  systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted
  tags:
    - node_exporter_run
  when: _config.changed

- name: Open port
  firewalld:
    port: "{{node_exporter_port}}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  ignore_errors: true

- name: set_fact for environment ns
  set_fact:
    _delegate_host: dsootansible01.cp.donna.ns.nl
    _openshift: https://portal.cp.donna.ns.nl:443
  when: inventory_hostname is search('ns.nl')

- name: set_fact for environment prorail
  set_fact:
    _delegate_host: dsoapansible01.cp.donna.prorail.nl
    _openshift: https://portal.cp.donna.prorail.nl:443
  when: inventory_hostname is search('dsoap|dsoprd') 

- name: set_fact for environment prorail uitwijk
  set_fact:
    _delegate_host: dsoapansible01.cp.donna.prorail.nl
    _openshift: https://portal.cp2.donna.prorail.nl:443
  when: inventory_hostname is search('dsouit')

- include_role:
    name: roledonna-scrapeconfig
  vars:
    _delegateHost: "{{_delegate_host}}"
    _OShift: "{{_openshift}}"