---

- name: define _firewall
  set_fact:
    _firewall:
      - { port: '' }

- name: add _*_firewall
  set_fact:
    _firewall:
      - "{{(_firewall+lookup('vars',item))|flatten|unique}}"
  with_items: "{{ lookup('varnames', '.+_firewall$').split(',') }}"

- debug:
    var: _firewall

- name: show ports and protocols
  debug:
    msg: "PORT={{item.port}} PROTO={{item.proto}}"
  with_items: "{{_firewall}}"
  when: item.port != ""

- name: open firewall ports 
  firewalld:
    port: "{{item.port}}/{{item.proto}}"
    permanent: true
    state: enabled
    immediate: true
  become: true
  with_items: "{{_firewall}}"
  when: item.port != ""

