---

- name: define _firewall
  set_fact:
    _firewall: []

- name: add _*_firewall
  set_fact:
    _firewall: "{{(_firewall+lookup('vars',item))|unique}}"
  with_items: "{{ lookup('varnames', '.+_firewall$').split(',') }}"

- name: get open ports
  shell: |
    firewall-cmd --list-all | grep -P '^\s+ports:' | tr ' ' '\n' | grep -P '^\d+\/(tcp|udp)'
  become: true
  register: _open_ports
  
- name: open firewall ports 
  firewalld:
    port: "{{item}}"
    permanent: true
    state: enabled
    immediate: true
  become: true
  with_items: "{{_firewall}}"

- name: close firewall ports that should not be open
  firewalld:
    port: "{{item}}"
    permanent: true
    state: disabled
    immediate: true
  become: true
  with_items: "{{_open_ports.stdout_lines}}"
  when: item not in _firewall

