---

- name: Add _all_firewall
  set_fact:
    _firewall: "{{ _all_firewall | unique }}"
  when: _all_firewall is defined

- name: Add _gitea_firewall
  set_fact:
    _firewall: "{{ (_firewall + _gitea_firewall) | unique }}"
  when: _gitea_firewall is defined

- name: Add _httpd_firewall
  set_fact:
    _firewall: "{{ (_firewall + _httpd_firewall) | unique }}"
  when: _httpd_firewall is defined

- name: Add _hostvar_firewall
  set_fact:
    _firewall: "{{ (_firewall + _hostvar_firewall) | unique }}"
  when: _hostvar_firewall is defined
    
- name: show ports and protocols
  debug:
    msg: "PORT={{item.port}} PROTO={{item.proto}}"
  with_items: "{{_firewall}}"

- name: "open firewall ports" 
  firewalld:
    port: "{{item.port}}/{{item.proto}}"
    permanent: true
    state: enabled
    immediate: true
  become: true
  with_items: "{{_firewall}}"
