---

- name: set external and internal
  set_fact:
    _internal: "{{_image_registry_url}}{{outer_item.image}}-{{outer_item.arch}}"
    _external: "{{outer_item.ext}}{{outer_item.image}}-{{outer_item.arch}}"
    _arch: "{{outer_item.arch}}"

- debug:
    msg: "INTERNAL={{_internal}}, EXTERNAL={{_external}}, ARCH={{_arch}}"

- name: "create jenkins directories"
  file:
    path: "{{item.directory}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
    state: directory
  become: true
  with_items:
    - { directory: "/var/lib/build-images/jenkins",owner: "root" ,group: "root" ,mode: "0777" }

- name: "pull {{_image_registry_url}}{{hostvars[groups['jenkins'][0]]['_ubuntu_image']['image']}}-{{_arch}}"
  shell: |
    #podman pull --arch {{_arch}} --creds "registry:{{hostvars[groups['registry'][0]]['_registry_password']}}" {{_image_registry_url}}{{hostvars[groups['jenkins'][0]]['_ubuntu_image']['image']}}-{{_arch}}
    podman pull --arch {{_arch}} {{_image_registry_url}}{{hostvars[groups['jenkins'][0]]['_ubuntu_image']['image']}}-{{_arch}}
  become: true

- name: "clone jenkins in /var/lib/build-images/jenkins"
  git:
    repo: 'https://github.com/jenkinsci/docker.git'
    dest: /var/lib/build-images/jenkins
    force: true
  become: true

- name: "copy file to /var/lib/build-images/jenkins for podman build"
  template:
    src: "jenkins/Dockerfile.j2"
    dest: "/var/lib/build-images/jenkins/Dockerfile"
    owner: root
    group: root
    mode: 0666
  become: true

- name: "build jenkins image {{_arch}} {{_internal}}"
  shell: |
    cd /var/lib/build-images/jenkins
    podman build --arch {{_arch}} -t {{_internal}} -f /var/lib/build-images/jenkins/Dockerfile
  become: true
  register: _build
  #failed_when: false

- debug:
    var: _build.stdout

- name: "tag {{_internal}} {{_external}}"
  shell: |
    podman tag {{_internal}} {{_external}}
  become: true

- name: "push image to {{_external}} and {{_internal}}"
  shell: |
    podman login -u registry -p "{{hostvars[groups['registry'][0]]['_registry_password']}}" "{{_image_registry_url}}"
    podman push {{_internal}}
    podman login -u "{{_dockerio_username}}" -p "{{_dockerio_token}}" "{{_dockerio_url}}"
    podman push {{_external}}
  become: true

- name: "get image info after build"
  shell: |
    podman images --format "{{ '{{' }}.ID{{ '}}' }} {{ '{{' }}.Repository{{ '}}' }} {{ '{{' }}.Tag{{ '}}' }}  {{ '{{' }}.Digest{{ '}}' }}" | grep jenkins
  become: true
  register: _jenkins_image

- debug:
    var: _jenkins_image.stdout

- name: clean up build directory
  file: 
    path: /var/lib/build-images/jenkins
    state: absent
  become: true    
