---

- name: set external and internal
  set_fact:
    _internal: "{{_image_registry_url}}{{outer_item.image}}-{{outer_item.arch}}"
    _external: "{{outer_item.ext}}{{outer_item.image}}-{{outer_item.arch}}"
    _arch: "{{outer_item.arch}}"

- debug:
    msg: "INTERNAL={{_internal}}, EXTERNAL={{_external}}, ARCH={{_arch}}"

- name: "create openvpn directories"
  file:
    path: "{{item.directory}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
    state: directory
  become: true
  with_items:
    - { directory: "/var/lib/build-images/docker-openvpn",owner: "root" ,group: "root" ,mode: "0777" }

- name: "pull --arch {{_arch}} {{_image_registry_url}}{{hostvars[groups['openvpn'][0]]['_alpine_image']['image']}}-{{_arch}}"
  shell: |
    podman pull {{_image_registry_url}}{{hostvars[groups['openvpn'][0]]['_alpine_image']['image']}}-{{_arch}}
  become: true

- name: "clone docker-openvpn in /var/lib/build-images/docker-openvpn"
  git:
    repo: 'https://github.com/kylemanna/docker-openvpn.git'
    dest: /var/lib/build-images/docker-openvpn
    force: true
  become: true

- name: "copy files to /var/lib/build-images/docker-openvpn/ for podman build"
  template:
    src: "openvpn/Dockerfile.j2"
    dest: "/var/lib/build-images/docker-openvpn/Dockerfile"
    owner: root
    group: root
    mode: 0664
  become: true

- name: "build openvpn image {{_internal}}"
  shell: |
    cd /var/lib/build-images/docker-openvpn
    podman build --arch {{_arch}} -t {{_internal}} -f /var/lib/build-images/docker-openvpn/Dockerfile
  become: true
  register: _build
  failed_when: false

- debug:
    var: _build.stdout

- name: "tag {{_internal}} {{_external}}"
  shell: |
    podman tag {{_internal}} {{_external}}
  become: true

- name: "push image to {{_external}} and {{_internal}}"
  shell: |
    podman login -u registry -p "{{hostvars[groups['registry'][0]]['_registry_password']}}" "{{_image_registry_url}}"
    podman push {{_internal}}
    podman login -u "{{_dockerio_username}}" -p "{{_dockerio_token}}" "{{_dockerio_url}}"
    podman push {{_external}}
  become: true

- name: "get image info after build"
  shell: |
    podman images --format "{{ '{{' }}.ID{{ '}}' }} {{ '{{' }}.Repository{{ '}}' }} {{ '{{' }}.Tag{{ '}}' }}  {{ '{{' }}.Digest{{ '}}' }}" | grep openvpn
  become: true
  register: _openvpn_image

- debug:
    var: _openvpn_image.stdout

- name: clean up build directory
  file: 
    path: /var/lib/build-images/docker-openvpn
    state: absent
  become: true    
