---

- name: set external and internal
  set_fact:
    _internal: "{{_image_registry_url}}{{outer_item.image}}-{{outer_item.arch}}"
    _external: "{{outer_item.ext}}{{outer_item.image}}-{{outer_item.arch}}"
    _arch: "{{outer_item.arch}}"

- debug:
    msg: "INTERNAL={{_internal}}, EXTERNAL={{_external}}, ARCH={{_arch}}" 

- name: "create openvpn-exporter directories"
  file:
    path: "{{item.directory}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
    state: directory
  become: true
  with_items:
    - { directory: "/var/lib/build-images/openvpn_exporter",owner: "root" ,group: "root" ,mode: "0777" }

- name: "pull {{_image_registry_url}}{{hostvars[groups['openvpn'][0]]['_golang_buster_image']['image']}}-{{_arch}}"
  shell: |
    podman pull --arch {{_arch}} {{_image_registry_url}}{{hostvars[groups['openvpn'][0]]['_golang_buster_image']['image']}}-{{_arch}}
  become: true

- name: "clone https://github.com/kumina/openvpn_exporter.git in /var/lib/openvpn_exporter"
  git:
    repo: 'https://github.com/kumina/openvpn_exporter.git'
    dest: /var/lib/openvpn_exporter
    force: true
  become: true

- name: "copy files to /var/lib/openvpn_exporter/ for podman build"
  template:
    src: "openvpn_exporter/Dockerfile.j2"
    dest: "/var/lib/openvpn_exporter/Dockerfile"
    owner: root
    group: root
    mode: 0664
  become: true

- name: "build openvpn-exporter image {{_internal}}"
  shell: |
    cd /var/lib/openvpn_exporter
    podman build --arch {{_arch}} -t {{_internal}} -f /var/lib/openvpn_exporter/Dockerfile
  become: true
  register: _build
  failed_when: false

- debug:
    var: _build.stdout

- name: "tag {{_internal}} {{_external}}"
  shell: |
    podman tag {{_internal}} {{_external}}
  become: true

- name: "push image to {{_external}} and {{_internal}}"
  shell: |
    podman login -u registry -p "{{hostvars[groups['registry'][0]]['_registry_password']}}" "{{_image_registry_url}}"
    podman push {{_internal}}
    podman login -u "{{_dockerio_username}}" -p "{{_dockerio_token}}" "{{_dockerio_url}}"
    podman push {{_external}}
  become: true

- name: "get image info after build"
  shell: |
    podman images --format "{{ '{{' }}.ID{{ '}}' }} {{ '{{' }}.Repository{{ '}}' }} {{ '{{' }}.Tag{{ '}}' }}  {{ '{{' }}.Digest{{ '}}' }}" | grep openvpn-exporter
  become: true
  register: _openvpn_exporter_image

- debug:
    var: _openvpn_exporter_image.stdout

- name: clean up build directory
  file:
    path: /var/lib/build-images/openvpn_exporter
    state: absent
  become: true
   
