---
node_exporter_version: 1.0.0
node_exporter_binary_local_dir: ""
node_exporter_web_listen_address: "0.0.0.0:9100"
node_exporter_port: "9100"

node_exporter_textfile_dir: "/var/lib/node_exporter"

node_exporter_enabled_collectors:
  - systemd
  - textfile:
      directory: "{{ node_exporter_textfile_dir }}"
#  - filesystem:
#      ignored-mount-points: "^/(sys|proc|dev)($|/)"
#      ignored-fs-types: "^(sys|proc|auto)fs$"

node_exporter_disabled_collectors: []
node_exporter_checksum: fae88be0aa33c8ae22340723f9b4a4e519e67d2969da7a27751e755db7e75788
_nodeexporternodes: []
