---

- name: create piaware directories
  file:
    path: "{{item.directory}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
    state: directory
  become: true
  with_items:
    - { directory: "/var/lib/piaware",         owner: "root" ,group: "root" ,mode: "0777" }
    - { directory: "/var/lib/piaware/certs",   owner: "root" ,group: "root" ,mode: "0774" }
    - { directory: "/var/lib/piaware/haproxy", owner: "root" ,group: "root" ,mode: "0777" }

- name: set sysctl fs.inotify
  ansible.posix.sysctl:
    name: "{{item.name}}"
    value: "{{item.value}}"
    state: present
  become: true
  with_items:
    - { name: "fs.inotify.max_queued_events", value: "32768" }
    - { name: "fs.inotify.max_user_instances", value: "1024" }
    - { name: "fs.inotify.max_user_watches", value: "16384" }

- include_role:
    name: pull-images
  vars:
    _images:
      - _piaware_image
      - _dump1090exporter_image
      - _haproxy_image

- name: create /etc/modprobe.d/blacklist-rtl2832.conf
  copy:
    content: |
      blacklist dvb_usb_rtl28xxu
      blacklist dvb_usb_rtl28xxu
      blacklist dvb_usb_rtl2832u
      blacklist dvb_usb_v2
      blacklist e4000
      blacklist r820t
      blacklist rtl2830
      blacklist rtl_2830
      blacklist rtl2832
      blacklist rtl2832U
      blacklist rtl2832_sdr
      blacklist rtl2838
      blacklist RTL2838UHIDIR
    dest: /etc/modprobe.d/blacklist-rtl2832.conf
    owner: root
    group: root
    mode: 0664
  become: true

- name: create local /var/lib/certs directory for certs
  file:
    path: /var/lib/certs
    owner: root
    group: root
    mode: 0777
    state: directory
  delegate_to: localhost
  become: true

- name: fetch keys from /var/lib/letsencrypt/keys/letsencrypt/
  delegate_to: "{{hostvars[groups['letsencrypt'][0]]['_letsencrypt_inventory_hostname']}}"
  run_once: yes
  fetch:
    src: "/var/lib/letsencrypt/keys/letsencrypt/{{item}}"
    dest: "/var/lib/certs/"
    flat: yes
  become: true
  with_items:
    - privkey.pem
    - fullchain.pem

- name: copy cert and key to host
  copy:
    src: /var/lib/certs/{{item}}
    dest: /var/lib/piaware/certs/{{item}}
    owner: root
    group: root
    mode: 0664
  become: true
  with_items:
    - fullchain.pem
    - privkey.pem
  notify: _restart_haproxy

- name: create pem file
  ansible.builtin.assemble:
    src: /var/lib/piaware/certs/
    dest: /var/lib/piaware/haproxy/{{ _piaware_fqdn }}-crt-key.pem
    owner: root
    group: root
    mode: 0664
  become: true

- name: create haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /var/lib/piaware/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0666
  become: true
  notify: _restart_haproxy

- name: create piaware pod 
  containers.podman.podman_pod:
    name: piawarepod
    state: started
    ports:
      - 8443:8443
      - 9105:9105
  become: true

- name: create piaware container
  containers.podman.podman_container:
    name: piaware
    pod: piawarepod
    image: "{{_image_registry_url}}{{_piaware_image.image}}-{{_architecture}}"
    state: present
    device: /dev/bus/usb
    env:
      TZ: "{{_timezone}}"
      LAT: "{{_lat}}"
      LONG: "{{_long}}"
      FEEDER_ID: "{{_piaware_feeder_id}}"
      RECEIVER_TYPE: "rtlsdr"
      ALLOW_MLAT: "yes"
      MLAT_RESULTS: "yes"
      RTLSDR_GAIN: "{{_rtlsdr_gain}}"
      ALLOW_MODEAC: "yes"
    restart_policy: always
    conmon_pidfile: /run/piaware.pid
  become: true
  register: _piaware_container_created
  notify: _restart_piaware

- name: create systemd piaware file
  shell: |
    podman generate systemd --name piaware > /etc/systemd/system/piaware.service 
  become: true
  when: _piaware_container_created.changed
  notify: _restart_piaware

- name: create dump1090exporter container
  containers.podman.podman_container:
    name: dump1090exporter
    pod: piawarepod
    image: "{{_image_registry_url}}{{_dump1090exporter_image.image}}-{{_architecture}}"
    state: started
    env:
      TZ: "{{_timezone}}"
    command: [ '--debug','--url=http://localhost:8080/dump1090-fa' ]
    restart_policy: always
  become: true
  register: _dump1090exporter_container_created
  notify: _restart_dump1090exporter

- name: create systemd dump1090exporter file
  shell: |
    podman generate systemd --name dump1090exporter > /etc/systemd/system/dump1090exporter.service 
  become: true
  when: _dump1090exporter_container_created.changed
  notify: _restart_dump1090exporter

- name: create haproxy container
  containers.podman.podman_container:
    name: haproxy
    pod: piawarepod
    state: started
    image: "{{_image_registry_url}}{{_haproxy_image.image}}-{{_architecture}}"
    debug: true
    privileged: true
    volume:
      - /var/lib/piaware/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /var/lib/piaware/haproxy/{{ _piaware_fqdn }}-crt-key.pem:/{{ _piaware_fqdn }}-crt-key.pem
    conmon_pidfile: /run/haproxy.pid
    restart_policy: always
  become: true
  register: _haproxy_container_created
  notify: _restart_haproxy

- name: create systemd haproxy file
  shell: |
    podman generate systemd --name haproxy > /etc/systemd/system/haproxy.service 
  become: true
  when: _haproxy_container_created.changed
  notify: _restart_haproxy

- name: trigger handelers
  meta: flush_handlers

- name: containers state
  shell: |
    podman ps -a --format "{{ '{{' }}.Status{{ '}}' }}  {{ '{{' }}.Names{{ '}}' }}  {{ '{{' }}.ID{{ '}}' }}" --filter 'name={{item}}'
  register: _containers_state
  become: true
  with_items:
    - piaware
    - dump1090exporter
    - haproxy

- debug:
    var: _containers_state
    
