---

# Get home directory
- name: "Get home directory {{ item }}."
  shell: >
    getent passwd {{ item }} | cut -d: -f6
  changed_when: false
  register: user_home

# Create directory
- name: "Create a directory .kube if it does not exist."
  file:
    path: "/{{ user_home.stdout }}/.kube"
    state: directory
    mode: '0755'
    owner: "{{ item }}"
    group: "{{ item }}"
  become: true

# Copy credentials
- name: "Copies cluster admin credentials to {{ user_home.stdout }}/.kube"
  copy:
    src: '/etc/kubernetes/admin.conf'
    remote_src: yes
    dest: "{{ user_home.stdout }}/.kube/config"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0770
  become: true


