---

# Get home directory
- name: "Get home directory {{ item }}."
  shell: >
    getent passwd {{ item }} | cut -d: -f6
  changed_when: false
  register: user_home

# Create directory
- name: "Create a directory .kube if it does not exist."
  file:
    path: "/{{ user_home.stdout }}/.kube"
    state: directory
    mode: '0755'
    owner: "{{ item }}"
    group: "{{ item }}"
  become: true

# Copy credentials
- name: "Copies cluster admin credentials to {{ user_home.stdout }}/.kube"
  copy:
    src: '/etc/kubernetes/admin.conf'
    remote_src: yes
    dest: "{{ user_home.stdout }}/.kube/config"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0770
  become: true

- name: create serviceaccount k8sadmin and show clusteradmin token
  shell: |
    kubectl create serviceaccount k8sadmin -n kube-system || echo "already exists"
    kubectl create clusterrolebinding k8sadmin --clusterrole=cluster-admin --serviceaccount=kube-system:k8sadmin || echo "already exists"
    kubectl -n kube-system describe secret $(sudo kubectl -n kube-system get secret | (grep k8sadmin || echo "$_") | awk '{print $1}') | grep token: | awk '{print $2}'
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  become: true
  failed_when: false


