---

- name: install sealed secret client /usr/local/bin/kubeseal 
  shell: |
    cd /tmp
    wget https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz -O /tmp/helm-v3.7.1-linux-amd64.tar.gz
    tar -zxvf /tmp/helm-v3.7.1-linux-amd64.tar.gz
    mv -f /tmp/linux-amd64/helm /usr/local/bin/helm
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  become: true

