---


- name: install sealed secret client /usr/local/bin/kubeseal 
  shell: |
    wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.16.0/kubeseal-linux-amd64 -O /usr/local/bin/kubeseal
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  become: true

- name: set permissions /usr/local/bin/kubeseal
  file:
    path: /usr/local/bin/kubeseal
    owner: root
    group: root
    mode: 0775
  become: true

# create sealed-secrets key pair
# https://github.com/bitnami-labs/sealed-secrets/blob/main/docs/bring-your-own-certificates.md
- name: copy sealed-secrets key pair secret
  ansible.builtin.copy:
    src: vault-sealed-secrets-key-secret.yaml
    dest: /tmp/vault-sealed-secrets-key-secret.yaml
    owner: root
    group: root
    mode: 0660
  become: true
    
- name: create sealed-secrets key pair secret
  shell: |
    kubectl create -n kube-system -f /tmp/vault-sealed-secrets-key-secret.yaml || kubectl apply -n kube-system -f /tmp/vault-sealed-secrets-key-secret.yaml
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  become: true
  failed_when: false

- name: add sealed secrets helm chart
  shell: |
    /usr/local/bin/helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  become: true

- name: install sealed-secrets helm chart
  shell: |
    /usr/local/bin/helm install --namespace kube-system my-release sealed-secrets/sealed-secrets 
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  become: true


