---
- name: ensure chronyd is unmasked
  systemd:
    name: chronyd
    masked: no
  become: true

- name: enforce proper dso chrony.conf settings
  template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony.conf
  become: true
  notify: restart chronyd

- name: ensure chronyd is running and enabled
  service:
    name: chronyd
    state: started
    enabled: yes
  become: true
    
- meta: flush_handlers
