---
- name: copy init mongo scipt to host
  copy:
    src: init-mongo.sh
    dest: /tmp
    owner: root
    group: root
    mode: 0777
  become: true

- name: copy init mongo script to pod
  shell: |
    /usr/bin/podman cp /tmp/init-mongo.sh mongo:/tmp
  become: true

- name: Initiate mongo
  shell: |
    /usr/bin/podman exec \
       -e MONGO_INITDB_ROOT_USERNAME={{ mongo_root_username | default('root') }} \
       -e MONGO_INITDB_ROOT_PASSWORD={{ mongo_root_password | default('password') }} \   
       mongo /bin/bash -c /tmp/init-mongo.sh
  register: result
  become: true

- debug:
    msg: "init mongo result: {{ result.stdout }}"




