---
- name: copy init mongo scipt to host
  copy:
    src: init-mongo.sh
    dest: /tmp
    owner: root
    group: root
    mode: 0777
  become: true

- name: copy init mongo script to pod
  shell: |
    /usr/bin/podman cp /tmp/init-mongo.sh mongo:/tmp
  become: true

- name: Initiate mongo
  shell: |
    /usr/bin/podman exec mongo /bin/bash -c /tmp/init-mongo.sh
  register: result
  become: true

- debug:
    msg: "init mongo result: {{ result.stdout }}"



