---

- name: create directories
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0775
  with_items:
    - "/data/mongo/db"
    - "/data/mongo/dump"
  become: true

- name: create mongo unit
  template:
    src: mongo.j2
    dest: /etc/systemd/system/mongo.service
    owner: root
    group: root
    mode: 0775
  become: true
  notify: 
    - reload daemon mongo
    - restart mongo

- name: start mongo
  systemd:
    name: mongo
    state: started
    enabled: yes
  become: true

