---

- name: create directories
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0775
  with_item:
    - /data/mongo/db
    - /data/mongo/dump
  become: true

- name: create mongo unit
  template:
    src: templates/mongdump
  become: true

- name: create mongo unit
  template:
    src: templates/mongo.j2
    dest: /etc/systemd/system/mongo.service
    owner: root
    group: root
    mode: 0775
  become: true
