---

- name: create directories
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0777
  with_items:
    - /data/rocketchat/uploads
  become: true

- name: create rocketchat unit
  template:
    src: rocketchat.j2
    dest: /etc/systemd/system/rocketchat.service
    owner: root
    group: root
    mode: 0775
    force: yes
  become: true
  notify: restart rocketchat

- name: copy rocketchat main.sh script
  copy:
    scr: main.sh
    dest: /tmp
    owner: root
    group: root
    mode: 0777
  become: true

- name: start rocketchhat
  systemd:
    name: rocketchat
    state: started
    enabled: yes
  become: true

