---

- name: create directories
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0775
  with_item:
    - /data/mongo/db
    - /data/mongo/dump
  become: true

- name: create rocketchat unit
  template:
    src: templates/rocketchat.j2
    dest: /etc/systemd/system/rocketchat.service
    owner: root
    group: root
    mode: 0775
  become: true
  notify: restart rocketchat

- name: start rocketchhat
  systemd:
    name: rocketchat
    state: started
    enabled: yes
  become: true

