---

- name: create apache httpd directories
  file:
    path: "{{item.directory}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
    state: directory
  become: true
  with_items:
    - { directory: "/etc/podman-compose",owner: "root", group: "root", mode: "0775" }
    - { directory: "/var/lib/httpd",     owner: "httpd",group: "httpd",mode: "0775" }
    - { directory: "/var/lib/httpd/conf",owner: "httpd",group: "httpd",mode: "0775" }
    - { directory: "/var/lib/httpd/www", owner: "httpd",group: "httpd",mode: "0775" }
    - { directory: "/var/lib/httpd/www/health", owner: "httpd",group: "httpd",mode: "0775" }

- name: copy httpd.conf
  template:
    src: httpd.conf.j2
    dest: /var/lib/httpd/conf/httpd.conf
    owner: httpd
    group: httpd
    mode: 0664
  become: true
  notify: restart podman-compose

- name: create index.html
  copy:
    content: '<!DOCTYPE html><html>hello</html>'
    dest: /var/lib/httpd/www/index.html
    owner: httpd
    group: httpd
    mode: 0664
  become: true
  
- name: create health check
  copy:
    src: index.html
    dest: /var/lib/httpd/www/health/index.html
    owner: httpd
    group: httpd
    mode: 0664
  become: true

- name: copy podman-compose file for httpd
  template:
    src: httpd.yml.j2
    dest: /etc/podman-compose/httpd.yml
    owner: root
    group: root
    mode: 0664
  become: true
  notify: restart podman-compose

- name: pull apache httpd image
  shell: |
    podman pull docker.io/httpd:latest
  become: true
  notify: restart podman-compose

- name: Start podman-compose httpd
  command: |
    podman-compose -f /etc/podman-compose/httpd.yml up -d
  become: true

