apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  service_type: ClusterIP
  postgres_storage_class: nfs
  ingress_tls_secret: ingress-tls
  ingress_type: Ingress


