apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 1
  service_type: ClusterIP
  postgres_storage_class: nfs
  deployment_type: awx
  ingress_type: ingress
  ingress_tls_secret: ingress-tls
  ingress_annotations: |
    kubernetes.io/ingress.class: nginx
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  image: quay.io/ansible/awx
  image_version: 19.4.0


