---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: awx-ingress
  namespace: awx
spec:
  tls:
    - hosts:
      - awx-k8s.bachstraat20.duckdns.org
      # This assumes tls-secret exists and the SSL
      # certificate contains a CN for foo.bar.com
      secretName: ingress-tls
  rules:
    - host: awx-k8s.bachstraat20.duckdns.org
      http:
        paths:
        - path: /
          backend:
            # This assumes http-svc exists and routes to healthy endpoints
            serviceName: awx-service
            servicePort: 80
