---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: awx-ingress
  namespace: awx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
      - awx-k8s.bachstraat20.duckdns.org
    secretName: ingress-tls
  rules:
    - host: awx-k8s.bachstraat20.duckdns.org
      http:
        paths:
          - backend:
              serviceName: awx-service
              servicePort: 80
            path: /
            pathType: Prefix
