---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: awx-ingress
  namespace: awx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
      - awx-k8s.bachstraat20.duckdns.org
    secretName: ingress-tls
  rules:
  - host: awx-k8s.bachstraat20.duckdns.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: awx-service
            port:
              number: 80
