---

- debug:
    msg: "VAR:{{item}}"

   
- name: set external and internal
  set_fact:
    _image: "{{lookup('vars',item)}}"

- debug:
    msg: "IMAGE:{{_image}}"

- set_fact:
    _internal: "{{_image_registry_url}}{{_image.image}}-{{_architecture}}"
    _external: "{{_image.ext}}{{_image.image}}-{{_architecture}}"

- debug:
    msg: "INTERNAL:{{_internal}}, EXTERNAL:{{_external}}"

- block:
    - name: pull {{_internal}}
      shell: |
        podman login -u registry -p "{{hostvars[groups['registry'][0]]['_registry_password']}}" "{{_image_registry_url}}"
        podman pull {{_internal}}
      become: true
      register: _image_pulled

  rescue:
    - name: pull image {{_external}}
      shell: |
        podman pull {{_external}}
      become: true
      register: _image_pulled

    - name: tag {{_external}} {{_internal}}
      shell: |
        podman tag {{_external}} {{_internal}}
      become: true

  always:
    - debug:
        var: _image_pulled


