---
- name: _restart_haproxy
  systemd:
    name: haproxy
    state: restarted
  become: true

- name: _restart_keepalived
  systemd:
    name: keepalived
    state: restarted
  become: true

- name: _restart_rsyslog
  systemd:
    name: rsyslog
    state: restarted
  become: true

- name: _reload_networkmanager
  shell: |
    nmcli c u "{{item}}"
  loop:
    - "{{ _int_device_conn }}"
    - "{{ _ext_device_conn }}"
  become: true

