_blackbox_image_tag: latest
_blackbox_firewall:
  - 9115/tcp
_blackbox_packages:
  - podman
_blackbox_groups:
  - { group: 'blackbox',gid: '1040' }
_blackbox_users:
  - { user: 'blackbox',comment: 'user for blackbox',uid: '1040',groups: 'blackbox',create_home: 'false',shell: '/bin/nologin' }


