---
_jenkins_firewall:
  - 5000/tcp
  - 8443/tcp
_jenkins_groups:
  - { group: 'jenkins',gid: '1037' }
_jenkins_users:
  - { user: 'jenkins',comment: 'user for jenkins',uid: '1037',groups: 'jenkins',create_home: 'false',shell: '/bin/nologin' }
_jenkins_packages:
  - podman
_jenkins_image_tag: 2.262-alpine-arm64
_jenkins_plugins:
  - cloudbees-folder:latest
  - pipeline-stage-view:latest
  - ws-cleanup:latest
  #- credentials-binding:latest
  #- gradle:latest
  #- mailer:latest
  #- timestamper:latest
_packages_for_jenkins:
  - ansible 
  - ca-certificates 
  - curl 
  - git 
  - java-cacerts
  - jq
  - openssl 
  - openssh-client 
  - python 
  - rsync 
  - sudo 
  - tar 
  - wget 
  
