---

_alpine_image:
  ext: 'docker.io/'
  image: 'library/alpine:latest'

_golang_buster_image:
  ext: 'docker.io/'
  image: 'golang:1.14-buster'

_openvpn_image:
  build: 'openvpn'
  ext: 'docker.io/'  
  image: 'tedsluis/openvpn:latest'

_openvpnexporter_image:
  build: 'openvpn-exporter'
  ext: 'docker.io/'
  image: 'tedsluis/openvpn-exporter:latest'

_openvpn_firewall:
  - 1194/udp
  - 9176/tcp

_openvpn_packages:
  - podman

_openvpn_dns_server: 192.168.1.17

_openvpn_fqdn: openvpn.bachstraat20.duckdns.org

_openvpnexporter_targets:
  - openvpn.bachstraat20.duckdns.org:9176
