_prometheus_image_tag: latest
_prometheus_firewall:
  - 9090/tcp
_prometheus_packages:
  - podman
_prometheus_groups:
  - { group: 'prometheus',gid: '1038' }
_prometheus_users:
  - { user: 'prometheus',comment: 'user for prometheus',uid: '1038',groups: 'prometheus',create_home: 'false',shell: '/bin/nologin' }
_prometheus_url: prometheus.bachstraat20.duckdns.org
_blackbox_http_2xx_targets:
  - https://git.bachstraat20.duckdns.org:3000
  - https://grafana.bachstraat20.duckdns.org:3000
  - https://home.bachstraat20.duckdns.org:30443
  - https://home.bachstraat20.duckdns.org:31443
  - http://alertmanager.bachstraat20.duckdns.org:9093
  - http://prometheus.bachstraat20.duckdns.org:9090
  - http://home.bachstraat20.duckdns.org:30080
  - http://home.bachstraat20.duckdns.org:31080
  - http://pihole.bachstraat20.duckdns.org
  - http://192.168.11.1
  - http://192.168.1.254
  - http://192.168.11.200
  - http://192.168.11.201
_blackbox_http_nodeexporter_2xx_targets:
  - https://fed127.bachstraat20.duckdns.org:9100
  - https://fed130.bachstraat20.duckdns.org:9100
  - https://fed143.bachstraat20.duckdns.org:9100
  - https://fed149.bachstraat20.duckdns.org:9100
  - https://fed157.bachstraat20.duckdns.org:9100
  - https://fed159.bachstraat20.duckdns.org:9100
  - https://fed160.bachstraat20.duckdns.org:9100
_blackbox_http_jebnkins_2xx_targets:
  - https://jenkins.bachstraat20.duckdns.org:8443

