---

- name: "include Ansible secrets to get pihole password."
  include_vars: inventory/group_vars/vault.yaml

- name: create directories
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0777
  with_items:
    - /var/lib/pihole
    - /var/lib/pihole/etc-pihole
    - /var/lib/pihole/etc-dnsmasq.d
    - /var/lib/pihole/etc-lighttpd
  become: true

- name: create local /var/lib/certs directory for certs
  file:
    path: /var/lib/certs
    owner: root
    group: root
    mode: 0777
    state: directory
  delegate_to: localhost
  become: true

- name: fetch keys from /var/lib/letsencrypt/keys/letsencrypt/
  delegate_to: "{{hostvars[groups['letsencrypt'][0]]['_letsencrypt_inventory_hostname']}}"
  run_once: yes
  fetch:
    src: "/var/lib/letsencrypt/keys/letsencrypt/{{item}}"
    dest: "/var/lib/certs/"
    flat: yes
  become: true
  with_items:
    - privkey.pem
    - cert.pem

- name: create combined.pem
  delegate_to: localhost
  shell: |
    cat /var/lib/certs/privkey.pem /var/lib/certs/cert.pem > /var/lib/certs/combined.pem
  become: true

- name: set permissions /tmp/certs/combined.pem
  delegate_to: localhost
  file:
    path: /var/lib/certs/combined.pem
    mode: 0664
  become: true

- name: place cert and key
  copy:
    src: "/var/lib/certs/combined.pem"
    dest: "/var/lib/pihole/etc-pihole/combined.pem"
    owner: root
    group: root
    mode: 0664
  become: true
  notify: 
    - reload daemon pihole
    - restart pihole

- name: copy /var/lib/pihole/etc-lighttpd/external.conf
  template:
    src: external.conf.j2
    dest: /var/lib/pihole/etc-lighttpd/external.conf
    owner: root
    group: root
    mode: 0775
    force: yes
  become: true
  notify:
    - reload daemon pihole 
    - restart pihole

- name: create pihole unit
  template:
    src: pihole.j2
    dest: /etc/systemd/system/pihole.service
    owner: root
    group: root
    mode: 0775
    force: yes
  become: true
  notify:
    - reload daemon pihole 
    - restart pihole

- name: start pihole
  systemd:
    name: pihole
    state: started
    enabled: yes
  become: true

- name: trigger handelers
  meta: flush_handlers

